In [1]:
import pandas as pd

read csv file

In [4]:
df1 = pd.read_csv("data_of_employee.csv")

In [15]:
df1.shape

(500, 8)

In [5]:
df1.head()

,emp_id,emp_name,department,city,salary,experience,hire_date,performance_score
0,1,Ashish Verma,Finance,Mumbai,112000,7,2016-07-25,1
1,2,Sunita Mehta,Operations,Hyderabad,48000,1,2016-01-19,2
2,3,Isha Kumar,Operations,Chandigarh,70000,17,2023-01-11,5
3,4,Rajesh Mishra,Marketing,Ahmedabad,148000,8,2024-09-30,1
4,5,Chetan Sethi,HR,Mumbai,67000,4,2025-09-25,3

In [6]:
df1.columns

Index(['emp_id', 'emp_name', 'department', 'city', 'salary', 'experience',
       'hire_date', 'performance_score'],
      dtype='str')

In [8]:
url = "https://github.com/datasciencekibaatein/EDA-on-Datasets/raw/main/EDA_Customer_Churn/Customer_churn_dataset.csv"

df2 = pd.read_csv(url)

In [9]:
df2.head()

,Customer_ID,Age,Gender,Annual_Income,Spending_Score,City,Purchase_Count,Avg_Order_Value,Membership,Churn
0,1001,56.0,Female,762956.0,16,Chennai,11,2854.54,Platinum,0
1,1002,46.0,Male,788873.0,8,Bangalore,9,3231.06,Platinum,0
2,1003,32.0,Male,215953.0,4,Pune,12,11097.03,Silver,0
3,1004,60.0,Male,650328.0,4,Pune,10,2764.38,Gold,1
4,1005,25.0,Female,153267.0,56,Pune,17,3901.14,Gold,0

In [12]:
df3 = pd.read_csv("employee_data_semicolon.txt",sep=";")

df3.head()

,Employee_ID,Name,Age,Department,City,Salary,Experience_Years,Performance_Rating
0,EMP0001,Simran Sharma,34,Sales,Delhi,57013,6.9,4
1,EMP0002,Ananya Agarwal,46,Finance,Delhi,98245,7.4,1
2,EMP0003,Vikram Bansal,32,Data Science,Jaipur,48178,9.0,4
3,EMP0004,Kavya Gupta,47,IT,Hyderabad,89877,2.6,3
4,EMP0005,Isha Patel,35,Operations,Pune,87625,9.2,1

In [13]:
df3.columns

Index(['Employee_ID', 'Name', 'Age', 'Department', 'City', 'Salary',
       'Experience_Years', 'Performance_Rating'],
      dtype='str')

In [16]:
df4 = pd.read_csv("data_of_employee.csv",nrows=200)

In [18]:
df4.shape

(200, 8)

In [20]:
df4.shape[0]

200

In [23]:
df5 = pd.read_csv("data_of_employee.csv",skiprows=3)

df5.head(20)

     3          Isha Kumar  Operations Chandigarh   70000  17  2023-01-11  5
0    4       Rajesh Mishra   Marketing  Ahmedabad  148000   8  2024-09-30  1
1    5        Chetan Sethi          HR     Mumbai   67000   4  2025-09-25  3
2    6         Aryan Mehta   Marketing  Bengaluru  153000  11  2018-11-09  5
3    7         Karan Patel     Finance    Chennai   86000  17  2025-11-29  4
4    8      Arjun Banerjee          HR  Ahmedabad  113000  11  2017-02-26  1
5    9         Aman Mishra          HR  Bengaluru   52000   7  2019-04-06  3
6   10       Sachin Pillai       Sales      Delhi   66000  11  2022-07-08  3
7   11        Anjali Dutta     Finance     Jaipur  117000  17  2016-10-31  4
8   12  Pradeep Srivastava     Finance    Kolkata  138000   7  2024-06-14  1
9   13          Isha Patel          HR  Hyderabad   48000   8  2017-05-14  5
10  14        Mohit Saxena     Finance    Chennai  172000  12  2016-08-08  3
11  15        Ayush Tiwari     Finance    Kolkata  122000  17  2023-05-18  5
12  16          Rakesh Roy   Marketing      Delhi   62000   7  2020-09-18  4
13  17         Arnav Singh          IT     Jaipur  105000  20  2023-11-19  4
14  18         Vivek Gupta   Marketing  Hyderabad  104000  19  2020-12-07  3
15  19        Tanvi Sharma     Finance  Bengaluru  123000  17  2023-08-15  3
16  20        Ashish Reddy   Marketing     Jaipur   45000  14  2025-09-11  3
17  21       Simran Bansal  Operations  Bengaluru   83000  20  2024-06-09  5
18  22         Yash Chopra       Sales      Delhi  109000   5  2025-09-10  5
19  23         Aarav Dutta          HR    Chennai   54000   0  2025-06-02  3

In [25]:
df6 = pd.read_csv("data_of_employee.csv",usecols=['emp_id','department','experience','salary'])

df6.head(10)

   emp_id  department  salary  experience
0       1     Finance  112000           7
1       2  Operations   48000           1
2       3  Operations   70000          17
3       4   Marketing  148000           8
4       5          HR   67000           4
5       6   Marketing  153000          11
6       7     Finance   86000          17
7       8          HR  113000          11
8       9          HR   52000           7
9      10       Sales   66000          11

Read Excel files

In [26]:
df7 = pd.read_excel("dataset.xlsx")

df7

,OrderID,OrderDate,CustomerID,ProductID,StoreID,EmployeeID,Quantity,UnitPrice,DiscountPct,GrossSales,DiscountAmount,NetSales,TotalCost,GrossProfit,SalesChannel,PaymentMethod
0,ORD000001,2025-02-14,CUST0240,P0025,S024,E005,2,112531.49,0.00,225062.98,0.00,225062.98,123646.06,101416.92,Online,Cash
1,ORD000002,2025-08-02,CUST0244,P0040,S008,E024,10,115428.01,0.05,1154280.10,57714.00,1096566.10,765435.80,331130.30,Online,Bank Transfer
2,ORD000003,2025-02-28,CUST0435,P0008,S023,E022,3,110635.80,0.10,331907.40,33190.74,298716.66,245766.69,52949.97,Online,Credit Card
3,ORD000004,2026-10-06,CUST0113,P0051,S024,E005,3,96915.40,0.20,290746.20,58149.24,232596.96,157304.64,75292.32,In-Store,Bank Transfer
4,ORD000005,2026-09-08,CUST0002,P0076,S024,E041,1,56346.29,0.10,56346.29,5634.63,50711.66,28124.25,22587.41,In-Store,UPI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,ORD002496,2026-04-11,CUST0441,P0027,S015,E048,2,4717.71,0.05,9435.42,471.77,8963.65,4437.78,4525.87,In-Store,Cash
2496,ORD002497,2025-03-29,CUST0020,P0070,S003,E038,5,121925.40,0.00,609627.00,0.00,609627.00,309054.05,300572.95,Online,Bank Transfer
2497,ORD002498,2025-10-30,CUST0163,P0027,S015,E057,4,4838.33,0.00,19353.32,0.00,19353.32,8875.56,10477.76,In-Store,Bank Transfer
2498,ORD002499,2026-11-11,CUST0112,P0032,S001,E021,3,75468.26,0.10,226404.78,22640.48,203764.30,165100.95,38663.35,In-Store,UPI
2499,ORD002500,2026-03-11,CUST0313,P0007,S003,E038,5,59702.19,0.10,298510.95,29851.10,268659.85,192710.65,75949.20,Corporate,Bank Transfer

In [27]:
fact_sale = pd.read_excel("dataset.xlsx",sheet_name="Fact_Sales")

In [28]:
fact_sale.head()

,OrderID,OrderDate,CustomerID,ProductID,StoreID,EmployeeID,Quantity,UnitPrice,DiscountPct,GrossSales,DiscountAmount,NetSales,TotalCost,GrossProfit,SalesChannel,PaymentMethod
0,ORD000001,2025-02-14,CUST0240,P0025,S024,E005,2,112531.49,0.00,225062.98,0.00,225062.98,123646.06,101416.92,Online,Cash
1,ORD000002,2025-08-02,CUST0244,P0040,S008,E024,10,115428.01,0.05,1154280.10,57714.00,1096566.10,765435.80,331130.30,Online,Bank Transfer
2,ORD000003,2025-02-28,CUST0435,P0008,S023,E022,3,110635.80,0.10,331907.40,33190.74,298716.66,245766.69,52949.97,Online,Credit Card
3,ORD000004,2026-10-06,CUST0113,P0051,S024,E005,3,96915.40,0.20,290746.20,58149.24,232596.96,157304.64,75292.32,In-Store,Bank Transfer
4,ORD000005,2026-09-08,CUST0002,P0076,S024,E041,1,56346.29,0.10,56346.29,5634.63,50711.66,28124.25,22587.41,In-Store,UPI

In [29]:
products = pd.read_excel("dataset.xlsx",sheet_name="Dim_Products")
products.head(10)

,ProductID,ProductName,Category,SubCategory,ListPrice,CostRatio,UnitCost
0,P0001,Laptop 01,Electronics,Economy,71300.25,0.45,32085.11
1,P0002,Laptop 02,Electronics,Standard,16793.73,0.49,8228.93
2,P0003,Laptop 03,Electronics,Economy,104862.78,0.72,75501.20
3,P0004,Laptop 04,Electronics,Economy,88956.60,0.65,57821.79
4,P0005,Monitor 05,Electronics,Economy,64146.00,0.50,32073.00
5,P0006,Monitor 06,Electronics,Premium,83431.65,0.65,54230.57
6,P0007,Monitor 07,Electronics,Economy,58397.16,0.66,38542.13
7,P0008,Monitor 08,Electronics,Standard,109229.64,0.75,81922.23
8,P0009,Keyboard 09,Electronics,Economy,41278.61,0.72,29720.60
9,P0010,Keyboard 10,Electronics,Premium,8226.04,0.59,4853.36

In [31]:
products = pd.read_excel("dataset.xlsx",sheet_name="Dim_Products",index_col="ProductID")
products.head(10)

,ProductName,Category,SubCategory,ListPrice,CostRatio,UnitCost
ProductID,,,,,,
P0001,Laptop 01,Electronics,Economy,71300.25,0.45,32085.11
P0002,Laptop 02,Electronics,Standard,16793.73,0.49,8228.93
P0003,Laptop 03,Electronics,Economy,104862.78,0.72,75501.20
P0004,Laptop 04,Electronics,Economy,88956.60,0.65,57821.79
P0005,Monitor 05,Electronics,Economy,64146.00,0.50,32073.00
P0006,Monitor 06,Electronics,Premium,83431.65,0.65,54230.57
P0007,Monitor 07,Electronics,Economy,58397.16,0.66,38542.13
P0008,Monitor 08,Electronics,Standard,109229.64,0.75,81922.23
P0009,Keyboard 09,Electronics,Economy,41278.61,0.72,29720.60
P0010,Keyboard 10,Electronics,Premium,8226.04,0.59,4853.36

In [32]:
all_sheets = pd.read_excel("dataset.xlsx",sheet_name=None)

all_sheets

{'Fact_Sales':         OrderID  OrderDate CustomerID ProductID StoreID EmployeeID  Quantity  \
 0     ORD000001 2025-02-14   CUST0240     P0025    S024       E005         2
 1     ORD000002 2025-08-02   CUST0244     P0040    S008       E024        10
 2     ORD000003 2025-02-28   CUST0435     P0008    S023       E022         3
 3     ORD000004 2026-10-06   CUST0113     P0051    S024       E005         3
 4     ORD000005 2026-09-08   CUST0002     P0076    S024       E041         1
 ...         ...        ...        ...       ...     ...        ...       ...
 2495  ORD002496 2026-04-11   CUST0441     P0027    S015       E048         2
 2496  ORD002497 2025-03-29   CUST0020     P0070    S003       E038         5
 2497  ORD002498 2025-10-30   CUST0163     P0027    S015       E057         4
 2498  ORD002499 2026-11-11   CUST0112     P0032    S001       E021         3
 2499  ORD002500 2026-03-11   CUST0313     P0007    S003       E038         5

       UnitPrice  DiscountPct  GrossSales  DiscountAmount    NetSales  \
 0     112531.49         0.00   225062.98            0.00   225062.98
 1     115428.01         0.05  1154280.10        57714.00  1096566.10
 2     110635.80         0.10   331907.40        33190.74   298716.66
 3      96915.40         0.20   290746.20        58149.24   232596.96
 4      56346.29         0.10    56346.29         5634.63    50711.66
 ...         ...          ...         ...             ...         ...
 2495    4717.71         0.05     9435.42          471.77     8963.65
 2496  121925.40         0.00   609627.00            0.00   609627.00
 2497    4838.33         0.00    19353.32            0.00    19353.32
 2498   75468.26         0.10   226404.78        22640.48   203764.30
 2499   59702.19         0.10   298510.95        29851.10   268659.85

       TotalCost  GrossProfit SalesChannel  PaymentMethod
 0     123646.06    101416.92       Online           Cash
 1     765435.80    331130.30       Online  Bank Transfer
 2     245766.69     52949.97       Online    Credit Card
 3     157304.64     75292.32     In-Store  Bank Transfer
 4      28124.25     22587.41     In-Store            UPI
 ...         ...          ...          ...            ...
 2495    4437.78      4525.87     In-Store           Cash
 2496  309054.05    300572.95       Online  Bank Transfer
 2497    8875.56     10477.76     In-Store  Bank Transfer
 2498  165100.95     38663.35     In-Store            UPI
 2499  192710.65     75949.20    Corporate  Bank Transfer

 [2500 rows x 16 columns],
 'Fact_Returns':      ReturnID    OrderID ReturnDate           ReturnReason  ReturnQty
 0    RET00001  ORD001448 2025-09-16  Customer Changed Mind          1
 1    RET00002  ORD001115 2025-05-27              Defective          1
 2    RET00003  ORD001065 2026-10-13                Damaged          2
 3    RET00004  ORD002288 2025-07-08  Customer Changed Mind          1
 4    RET00005  ORD001538 2026-12-26  Customer Changed Mind          2
 ..        ...        ...        ...                    ...        ...
 175  RET00176  ORD000791 2025-04-18          Wrong Product          1
 176  RET00177  ORD000842 2026-11-19                Damaged          1
 177  RET00178  ORD000483 2026-01-31                Damaged          1
 178  RET00179  ORD001911 2026-08-20          Late Delivery          1
 179  RET00180  ORD000622 2026-07-16              Defective          1

 [180 rows x 5 columns],
 'Fact_Budget':      Year  MonthNo StoreID  SalesBudget  ProfitBudget
 0    2025        1    S001   2467714.63     718986.75
 1    2025        1    S002    999918.25     980464.02
 2    2025        1    S003    668822.11     498075.28
 3    2025        1    S004   2244365.54     752203.81
 4    2025        1    S005    670768.40     874774.78
 ..    ...      ...     ...          ...           ...
 595  2026       12    S021   1435216.59    1066716.86
 596  2026       12    S022   1686035.54     865238.32
 597  2026       12    S023   1126357.93     266248.54
 598  2026       12    S024    658162.05     759120.22
 599  2026       12    S025   2260116.41     923722.68

 [600 rows x 5 columns],
 'Dim_Customers':     CustomerID   CustomerName         Segment         City   Region  \
 0     CUST0001  Customer 0001        Consumer       Mumbai     West
 1     CUST0002  Customer 0002        Consumer    Hyderabad    South
 2     CUST0003  Customer 0003        Consumer  Bhubaneswar     East
 3     CUST0004  Customer 0004        Consumer       Bhopal  Central
 4     CUST0005  Customer 0005        Consumer     Guwahati     East
 ..         ...            ...             ...          ...      ...
 495   CUST0496  Customer 0496  Small Business    Hyderabad    South
 496   CUST0497  Customer 0497        Consumer       Nagpur  Central
 497   CUST0498  Customer 0498        Consumer        Kochi    South
 498   CUST0499  Customer 0499       Corporate        Surat     West
 499   CUST0500  Customer 0500        Consumer       Jaipur    North

      BirthDate  Gender CustomerType
 0   2013-05-18    Male      Regular
 1   2014-06-09  Female      Regular
 2   2018-03-11  Female          New
 3   2016-09-04  Female          New
 4   2004-10-08  Female        Loyal
 ..         ...     ...          ...
 495 2011-10-20    Male      Regular
 496 2015-01-23  Female      Regular
 497 2022-09-28  Female          New
 498 2009-08-04  Female          New
 499 2009-10-03    Male      Regular

 [500 rows x 8 columns],
 'Dim_Products':    ProductID    ProductName     Category SubCategory  ListPrice  CostRatio  \
 0      P0001      Laptop 01  Electronics     Economy   71300.25       0.45
 1      P0002      Laptop 02  Electronics    Standard   16793.73       0.49
 2      P0003      Laptop 03  Electronics     Economy  104862.78       0.72
 3      P0004      Laptop 04  Electronics     Economy   88956.60       0.65
 4      P0005     Monitor 05  Electronics     Economy   64146.00       0.50
 ..       ...            ...          ...         ...        ...        ...
 75     P0076  Power Bank 76  Accessories     Economy   58592.19       0.48
 76     P0077    Desk Mat 77  Accessories    Standard    3086.14       0.56
 77     P0078    Desk Mat 78  Accessories     Economy   75905.97       0.66
 78     P0079    Desk Mat 79  Accessories    Standard     879.74       0.49
 79     P0080    Desk Mat 80  Accessories    Standard   36052.95       0.48

     UnitCost
 0   32085.11
 1    8228.93
 2   75501.20
 3   57821.79
 4   32073.00
 ..       ...
 75  28124.25
 76   1728.24
 77  50097.94
 78    431.07
 79  17305.42

 [80 rows x 7 columns],
 'Dim_Stores':    StoreID StoreName         City   Region          StoreType OpeningDate
 0     S001  Store 01      Chennai    South             Outlet  2024-06-27
 1     S002  Store 02      Chennai    South               Mall  2024-02-10
 2     S003  Store 03         Pune     West  Business District  2021-05-23
 3     S004  Store 04  Bhubaneswar     East               Mall  2022-05-08
 4     S005  Store 05        Delhi    North               Mall  2022-08-21
 5     S006  Store 06       Bhopal  Central               Mall  2020-12-12
 6     S007  Store 07      Kolkata     East               Mall  2023-09-10
 7     S008  Store 08       Jaipur    North  Business District  2022-01-09
 8     S009  Store 09      Chennai    South             Outlet  2022-01-19
 9     S010  Store 10        Surat     West             Outlet  2024-09-25
 10    S011  Store 11       Mumbai     West             Outlet  2020-11-11
 11    S012  Store 12       Mumbai     West  Business District  2022-02-03
 12    S013  Store 13        Kochi    South  Business District  2023-05-05
 13    S014  Store 14      Chennai    South             Outlet  2018-12-20
 14    S015  Store 15      Kolkata     East             Outlet  2022-01-04
 15    S016  Store 16   Chandigarh    North               Mall  2022-12-15
 16    S017  Store 17       Jaipur    North             Outlet  2020-03-28
 17    S018  Store 18   Chandigarh    North               Mall  2020-06-07
 18    S019  Store 19       Raipur  Central  Business District  2019-09-25
 19    S020  Store 20       Jaipur    North  Business District  2018-05-17
 20    S021  Store 21  Bhubaneswar     East             Outlet  2022-01-15
 21    S022  Store 22         Pune     West  Business District  2020-03-29
 22    S023  Store 23       Nagpur  Central               Mall  2018-07-17
 23    S024  Store 24    Ahmedabad     West               Mall  2024-09-14
 24    S025  Store 25    Hyderabad    South        High Street  2023-05-03,
 'Dim_Employees':    EmployeeID  EmployeeName              Role StoreID
 0        E001  Employee 001   Sales Executive    S025
 1        E002  Employee 002   Sales Associate    S010
 2        E003  Employee 003   Sales Executive    S021
 3        E004  Employee 004   Sales Associate    S013
 4        E005  Employee 005   Sales Executive    S024
 5        E006  Employee 006   Sales Associate    S017
 6        E007  Employee 007   Sales Associate    S025
 7        E008  Employee 008   Sales Executive    S021
 8        E009  Employee 009     Store Manager    S019
 9        E010  Employee 010   Sales Associate    S010
 10       E011  Employee 011   Sales Executive    S022
 11       E012  Employee 012  Regional Manager    S009
 12       E013  Employee 013     Store Manager    S016
 13       E014  Employee 014   Sales Executive    S014
 14       E015  Employee 015   Sales Associate    S009
 15       E016  Employee 016   Sales Executive    S009
 16       E017  Employee 017   Sales Executive    S005
 17       E018  Employee 018   Sales Associate    S002
 18       E019  Employee 019   Sales Executive    S009
 19       E020  Employee 020   Sales Associate    S022
 20       E021  Employee 021   Sales Associate    S001
 21       E022  Employee 022   Sales Associate    S023
 22       E023  Employee 023   Sales Associate    S002
 23       E024  Employee 024   Sales Executive    S008
 24       E025  Employee 025   Sales Associate    S018
 25       E026  Employee 026   Sales Associate    S006
 26       E027  Employee 027   Sales Associate    S021
 27       E028  Employee 028   Sales Associate    S022
 28       E029  Employee 029   Sales Executive    S004
 29       E030  Employee 030   Sales Executive    S011
 30       E031  Employee 031   Sales Executive    S025
 31       E032  Employee 032   Sales Associate    S022
 32       E033  Employee 033     Store Manager    S012
 33       E034  Employee 034   Sales Executive    S010
 34       E035  Employee 035   Sales Executive    S005
 35       E036  Employee 036   Sales Associate    S002
 36       E037  Employee 037   Sales Executive    S004
 37       E038  Employee 038   Sales Associate    S003
 38       E039  Employee 039     Store Manager    S015
 39       E040  Employee 040   Sales Executive    S012
 40       E041  Employee 041     Store Manager    S024
 41       E042  Employee 042   Sales Associate    S025
 42       E043  Employee 043  Regional Manager    S006
 43       E044  Employee 044   Sales Associate    S023
 44       E045  Employee 045   Sales Associate    S015
 45       E046  Employee 046   Sales Executive    S012
 46       E047  Employee 047   Sales Executive    S021
 47       E048  Employee 048   Sales Executive    S015
 48       E049  Employee 049   Sales Associate    S002
 49       E050  Employee 050   Sales Executive    S007
 50       E051  Employee 051   Sales Executive    S021
 51       E052  Employee 052   Sales Executive    S023
 52       E053  Employee 053     Store Manager    S020
 53       E054  Employee 054   Sales Associate    S012
 54       E055  Employee 055   Sales Executive    S011
 55       E056  Employee 056   Sales Associate    S013
 56       E057  Employee 057  Regional Manager    S015
 57       E058  Employee 058   Sales Associate    S011
 58       E059  Employee 059   Sales Associate    S023
 59       E060  Employee 060   Sales Associate    S008,
 'Dim_Calendar':           Date  Year  MonthNo     Month Quarter YearMonth    Weekday  WeekNo  \
 0   2025-01-01  2025        1   January      Q1   2025-01  Wednesday       1
 1   2025-01-02  2025        1   January      Q1   2025-01   Thursday       1
 2   2025-01-03  2025        1   January      Q1   2025-01     Friday       1
 3   2025-01-04  2025        1   January      Q1   2025-01   Saturday       1
 4   2025-01-05  2025        1   January      Q1   2025-01     Sunday       1
 ..         ...   ...      ...       ...     ...       ...        ...     ...
 725 2026-12-27  2026       12  December      Q4   2026-12     Sunday      52
 726 2026-12-28  2026       12  December      Q4   2026-12     Monday      53
 727 2026-12-29  2026       12  December      Q4   2026-12    Tuesday      53
 728 2026-12-30  2026       12  December      Q4   2026-12  Wednesday      53
 729 2026-12-31  2026       12  December      Q4   2026-12   Thursday      53

      IsWeekend
 0        False
 1        False
 2        False
 3         True
 4         True
 ..         ...
 725       True
 726      False
 727      False
 728      False
 729      False

 [730 rows x 9 columns]}

In [34]:
all_sheets['Fact_Sales']

,OrderID,OrderDate,CustomerID,ProductID,StoreID,EmployeeID,Quantity,UnitPrice,DiscountPct,GrossSales,DiscountAmount,NetSales,TotalCost,GrossProfit,SalesChannel,PaymentMethod
0,ORD000001,2025-02-14,CUST0240,P0025,S024,E005,2,112531.49,0.00,225062.98,0.00,225062.98,123646.06,101416.92,Online,Cash
1,ORD000002,2025-08-02,CUST0244,P0040,S008,E024,10,115428.01,0.05,1154280.10,57714.00,1096566.10,765435.80,331130.30,Online,Bank Transfer
2,ORD000003,2025-02-28,CUST0435,P0008,S023,E022,3,110635.80,0.10,331907.40,33190.74,298716.66,245766.69,52949.97,Online,Credit Card
3,ORD000004,2026-10-06,CUST0113,P0051,S024,E005,3,96915.40,0.20,290746.20,58149.24,232596.96,157304.64,75292.32,In-Store,Bank Transfer
4,ORD000005,2026-09-08,CUST0002,P0076,S024,E041,1,56346.29,0.10,56346.29,5634.63,50711.66,28124.25,22587.41,In-Store,UPI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,ORD002496,2026-04-11,CUST0441,P0027,S015,E048,2,4717.71,0.05,9435.42,471.77,8963.65,4437.78,4525.87,In-Store,Cash
2496,ORD002497,2025-03-29,CUST0020,P0070,S003,E038,5,121925.40,0.00,609627.00,0.00,609627.00,309054.05,300572.95,Online,Bank Transfer
2497,ORD002498,2025-10-30,CUST0163,P0027,S015,E057,4,4838.33,0.00,19353.32,0.00,19353.32,8875.56,10477.76,In-Store,Bank Transfer
2498,ORD002499,2026-11-11,CUST0112,P0032,S001,E021,3,75468.26,0.10,226404.78,22640.48,203764.30,165100.95,38663.35,In-Store,UPI
2499,ORD002500,2026-03-11,CUST0313,P0007,S003,E038,5,59702.19,0.10,298510.95,29851.10,268659.85,192710.65,75949.20,Corporate,Bank Transfer

In [36]:
all_sheets['Dim_Customers']

,CustomerID,CustomerName,Segment,City,Region,BirthDate,Gender,CustomerType
0,CUST0001,Customer 0001,Consumer,Mumbai,West,2013-05-18,Male,Regular
1,CUST0002,Customer 0002,Consumer,Hyderabad,South,2014-06-09,Female,Regular
2,CUST0003,Customer 0003,Consumer,Bhubaneswar,East,2018-03-11,Female,New
3,CUST0004,Customer 0004,Consumer,Bhopal,Central,2016-09-04,Female,New
4,CUST0005,Customer 0005,Consumer,Guwahati,East,2004-10-08,Female,Loyal
...,...,...,...,...,...,...,...,...
495,CUST0496,Customer 0496,Small Business,Hyderabad,South,2011-10-20,Male,Regular
496,CUST0497,Customer 0497,Consumer,Nagpur,Central,2015-01-23,Female,Regular
497,CUST0498,Customer 0498,Consumer,Kochi,South,2022-09-28,Female,New
498,CUST0499,Customer 0499,Corporate,Surat,West,2009-08-04,Female,New
499,CUST0500,Customer 0500,Consumer,Jaipur,North,2009-10-03,Male,Regular

In [37]:
all_sheets.keys()

dict_keys(['Fact_Sales', 'Fact_Returns', 'Fact_Budget', 'Dim_Customers', 'Dim_Products', 'Dim_Stores', 'Dim_Employees', 'Dim_Calendar'])

Read_json file

In [38]:
df = pd.read_json("employees_json.json")

In [39]:
df.head()

,employee_id,name,age,gender,department,job_role,city,salary,joining_date,experience_years,performance_rating,projects_completed,employment_status
0,EMP0001,Arjun Sharma,28,Male,IT,Software Engineer,Mumbai,118696,2024-10-08,8.9,5.0,2,On Leave
1,EMP0002,Vivaan Sharma,28,Male,Data Science,ML Engineer,Pune,115181,2024-08-11,8.4,4.5,4,On Leave
2,EMP0003,Simran Gupta,21,Male,Operations,Process Analyst,Jaipur,74597,2026-06-09,3.3,3.5,13,Active
3,EMP0004,Arjun Verma,32,Female,Sales,Account Manager,Hyderabad,35695,2024-04-09,8.8,5.0,2,On Leave
4,EMP0005,Aditya Malhotra,41,Female,Marketing,SEO Specialist,Pune,39116,2026-04-29,0.5,3.5,13,Active

# Write the data

In [ ]:
sale = pd.read_excel("dataset.xlsx",sheet_name='Fact_Sales')
products = pd.read_excel("dataset.xlsx",sheet_name='Dim_Products')
customers = pd.read_excel("dataset.xlsx",sheet_name='Dim_Customers')

In [44]:
sale.info()

<class 'pandas.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   OrderID         2500 non-null   str
 1   OrderDate       2500 non-null   datetime64[us]
 2   CustomerID      2500 non-null   str
 3   ProductID       2500 non-null   str
 4   StoreID         2500 non-null   str
 5   EmployeeID      2500 non-null   str
 6   Quantity        2500 non-null   int64
 7   UnitPrice       2500 non-null   float64
 8   DiscountPct     2500 non-null   float64
 9   GrossSales      2500 non-null   float64
 10  DiscountAmount  2500 non-null   float64
 11  NetSales        2500 non-null   float64
 12  TotalCost       2500 non-null   float64
 13  GrossProfit     2500 non-null   float64
 14  SalesChannel    2500 non-null   str
 15  PaymentMethod   2500 non-null   str
dtypes: datetime64[us](1), float64(7), int64(1), str(7)
memory usage: 423.1 KB

In [47]:
sale.to_csv("sale.csv",index=False)

In [46]:
sale.head()

,OrderID,OrderDate,CustomerID,ProductID,StoreID,EmployeeID,Quantity,UnitPrice,DiscountPct,GrossSales,DiscountAmount,NetSales,TotalCost,GrossProfit,SalesChannel,PaymentMethod
0,ORD000001,2025-02-14,CUST0240,P0025,S024,E005,2,112531.49,0.00,225062.98,0.00,225062.98,123646.06,101416.92,Online,Cash
1,ORD000002,2025-08-02,CUST0244,P0040,S008,E024,10,115428.01,0.05,1154280.10,57714.00,1096566.10,765435.80,331130.30,Online,Bank Transfer
2,ORD000003,2025-02-28,CUST0435,P0008,S023,E022,3,110635.80,0.10,331907.40,33190.74,298716.66,245766.69,52949.97,Online,Credit Card
3,ORD000004,2026-10-06,CUST0113,P0051,S024,E005,3,96915.40,0.20,290746.20,58149.24,232596.96,157304.64,75292.32,In-Store,Bank Transfer
4,ORD000005,2026-09-08,CUST0002,P0076,S024,E041,1,56346.29,0.10,56346.29,5634.63,50711.66,28124.25,22587.41,In-Store,UPI

In [48]:
sale.to_excel("sale.xlsx")

In [53]:
sale.to_excel("cmpny.xlsx",sheet_name="Orders")

In [52]:
products.to_excel("cmpny.xlsx",sheet_name="Products")

In [54]:
with pd.ExcelWriter("company.xlsx") as writer:
    sale.to_excel(
        writer,
        sheet_name="Orders",
        index=False
    )
    products.to_excel(
        writer,
        sheet_name="Products",
        index=False
    )
    customers.to_excel(
        writer,
        sheet_name="Customers",
        index=False
    )

In [56]:
df.to_json("dummy.json")