In [5]:
import pandas as pd

# Datastructure in pandas

1. Series(1D)
2. Dataframe(2D)

In [6]:
employees = {
    'emp_name':['rahul','neha','ram','sohit'],
    'salary':[32000,33000,34000,20000],
    'age':[23,22,24,25]
}

In [7]:
df = pd.DataFrame(employees)

In [11]:
print(df)
print(type(df))

  emp_name  salary  age
0    rahul   32000   23
1     neha   33000   22
2      ram   34000   24
3    sohit   20000   25
<class 'pandas.DataFrame'>

In [12]:
print(df['age'])
print(type(df['age']))

0    23
1    22
2    24
3    25
Name: age, dtype: int64
<class 'pandas.Series'>

In [10]:
salary = [34000,35000,23000,34000]

sr = pd.Series(salary)
print(sr)
print(type(sr))

0    34000
1    35000
2    23000
3    34000
dtype: int64
<class 'pandas.Series'>

### Series Functions

In [16]:
slry = [34000,35000,23000,34000]
# salary = pd.Series(slry,index=[x for x in range(1,5)])
salary = pd.Series(slry,index=['a','b','c','d'])


print(salary)

a    34000
b    35000
c    23000
d    34000
dtype: int64

In [18]:
print(salary.dtypes)

int64

In [20]:
print("salary pool:",salary.sum())

salary pool: 126000

In [21]:
print("salary avg:",salary.mean())

salary avg: 31500.0

In [22]:
print("salary std:",salary.std())

salary std: 5686.2407030773265

In [23]:
print("Descriptive information")

print(salary.describe())

Descriptive information
count        4.000000
mean     31500.000000
std       5686.240703
min      23000.000000
25%      31250.000000
50%      34000.000000
75%      34250.000000
max      35000.000000
dtype: float64

In [28]:
salary['b']

35000

# Dataframe

In [ ]:
employees = {
    'emp_name':['rahul','neha','ram','sohit','rishabh','Rohit'],
    'salary':[32000,33000,34000,20000,45000,35000],
    'age':[23,22,24,25,30,26]
}

In [51]:
df = pd.DataFrame(employees,index=[f"Employee_{x}" for x in range(1,7)])
df

           emp_name  salary  age
Employee_1    rahul   32000   23
Employee_2     neha   33000   22
Employee_3      ram   34000   24
Employee_4    sohit   20000   25
Employee_5  rishabh   45000   30
Employee_6    Rohit   35000   26

In [41]:
import numpy as np

matrix = np.array([
    [23,35000,4.4],
    [25,45000,4.3],
    [33,55000,3.8]
])

In [42]:
df1 = pd.DataFrame(matrix,index=[f"Employee_{x}" for x in range(1,4)],columns=['age','salary','rank'])
df1

             age   salary  rank
Employee_1  23.0  35000.0   4.4
Employee_2  25.0  45000.0   4.3
Employee_3  33.0  55000.0   3.8

In [39]:
df

           emp_name  salary  age
Employee_1    rahul   32000   23
Employee_2     neha   33000   22
Employee_3      ram   34000   24
Employee_4    sohit   20000   25

In [38]:
df.shape

(4, 3)

In [40]:
df.dtypes

emp_name      str
salary      int64
age         int64
dtype: object

In [43]:
df1.dtypes

age       float64
salary    float64
rank      float64
dtype: object

In [44]:
df.columns

Index(['emp_name', 'salary', 'age'], dtype='str')

In [45]:
df.values

array([['rahul', 32000, 23],
       ['neha', 33000, 22],
       ['ram', 34000, 24],
       ['sohit', 20000, 25]], dtype=object)

In [ ]:
df.head() # by default returns 5 records from top

           emp_name  salary  age
Employee_1    rahul   32000   23
Employee_2     neha   33000   22
Employee_3      ram   34000   24
Employee_4    sohit   20000   25
Employee_5  rishabh   45000   30

In [53]:
df.tail()

           emp_name  salary  age
Employee_2     neha   33000   22
Employee_3      ram   34000   24
Employee_4    sohit   20000   25
Employee_5  rishabh   45000   30
Employee_6    Rohit   35000   26

In [54]:
df.head(3)

           emp_name  salary  age
Employee_1    rahul   32000   23
Employee_2     neha   33000   22
Employee_3      ram   34000   24

In [55]:
df.tail(3)

           emp_name  salary  age
Employee_4    sohit   20000   25
Employee_5  rishabh   45000   30
Employee_6    Rohit   35000   26

In [56]:
df.describe()

             salary        age
count      6.000000   6.000000
mean   33166.666667  25.000000
std     7985.403350   2.828427
min    20000.000000  22.000000
25%    32250.000000  23.250000
50%    33500.000000  24.500000
75%    34750.000000  25.750000
max    45000.000000  30.000000

In [62]:
df[['salary','age']].mean()

salary    33166.666667
age          25.000000
dtype: float64