In [498]:
import pandas as pd

In [499]:
df = pd.read_csv("unclean_data.csv")

In [500]:
df.head()

,Employee_ID,Name,Age,Gender,City,Department,Salary,Experience_Years,Joining_Date,Education,Employment_Type,Employment_Status,Product,Quantity,Sales_Amount,Discount_Percent,Remote_Work,Performance_Rating
0,EMP0001,Aarav Sharma,28.0,Female,Hyderabad,HR,31556.0,5.0,2026-04-26 00:00:00,Graduate,Full-time,Resigned,Laptop,1,6240.0,13.0,Yes,Excellent
1,EMP0002,Vivaan Verma,56.0,Female,Hyderabad,Data Analytics,77124.0,19.0,2026-01-11 00:00:00,Diploma,Full-time,Inactive,Keyboard,7,22398.0,17.0,Yes,Good
2,EMP0003,Aditya Singh,42.0,Female,Mumbai,Operations,51793.0,12.0,2019-01-15 00:00:00,High School,Contract,Active,Keyboard,8,35242.0,7.0,No,Excellent
3,EMP0004,Arjun Mehta,NaN,Female,Amritsar,HR,101854.0,3.0,2025-01-18 00:00:00,Graduate,Part-time,On Leave,Laptop,4,6719.0,24.0,No,Poor
4,EMP0005,Rohan Gupta,44.0,Female,Hyderabad,IT,67638.0,3.0,2022-02-25 00:00:00,High School,Part-time,Inactive,Phone,8,24967.0,17.0,Yes,Average

In [501]:
df.shape[0]

200

In [502]:
df.isnull().sum()

Employee_ID           0
Name                  1
Age                   3
Gender                1
City                  3
Department            2
Salary                2
Experience_Years      1
Joining_Date          1
Education             2
Employment_Type       1
Employment_Status     1
Product               1
Quantity              0
Sales_Amount          1
Discount_Percent      1
Remote_Work           2
Performance_Rating    1
dtype: int64

In [503]:
df.isnull().mean()*100

Employee_ID           0.0
Name                  0.5
Age                   1.5
Gender                0.5
City                  1.5
Department            1.0
Salary                1.0
Experience_Years      0.5
Joining_Date          0.5
Education             1.0
Employment_Type       0.5
Employment_Status     0.5
Product               0.5
Quantity              0.0
Sales_Amount          0.5
Discount_Percent      0.5
Remote_Work           1.0
Performance_Rating    0.5
dtype: float64

In [504]:
df.dtypes

Employee_ID           str
Name                  str
Age                   str
Gender                str
City                  str
Department            str
Salary                str
Experience_Years      str
Joining_Date          str
Education             str
Employment_Type       str
Employment_Status     str
Product               str
Quantity              str
Sales_Amount          str
Discount_Percent      str
Remote_Work           str
Performance_Rating    str
dtype: object

In [505]:
df.notnull().sum()

Employee_ID           200
Name                  199
Age                   197
Gender                199
City                  197
Department            198
Salary                198
Experience_Years      199
Joining_Date          199
Education             198
Employment_Type       199
Employment_Status     199
Product               199
Quantity              200
Sales_Amount          199
Discount_Percent      199
Remote_Work           198
Performance_Rating    199
dtype: int64

In [506]:
df.head()

,Employee_ID,Name,Age,Gender,City,Department,Salary,Experience_Years,Joining_Date,Education,Employment_Type,Employment_Status,Product,Quantity,Sales_Amount,Discount_Percent,Remote_Work,Performance_Rating
0,EMP0001,Aarav Sharma,28.0,Female,Hyderabad,HR,31556.0,5.0,2026-04-26 00:00:00,Graduate,Full-time,Resigned,Laptop,1,6240.0,13.0,Yes,Excellent
1,EMP0002,Vivaan Verma,56.0,Female,Hyderabad,Data Analytics,77124.0,19.0,2026-01-11 00:00:00,Diploma,Full-time,Inactive,Keyboard,7,22398.0,17.0,Yes,Good
2,EMP0003,Aditya Singh,42.0,Female,Mumbai,Operations,51793.0,12.0,2019-01-15 00:00:00,High School,Contract,Active,Keyboard,8,35242.0,7.0,No,Excellent
3,EMP0004,Arjun Mehta,NaN,Female,Amritsar,HR,101854.0,3.0,2025-01-18 00:00:00,Graduate,Part-time,On Leave,Laptop,4,6719.0,24.0,No,Poor
4,EMP0005,Rohan Gupta,44.0,Female,Hyderabad,IT,67638.0,3.0,2022-02-25 00:00:00,High School,Part-time,Inactive,Phone,8,24967.0,17.0,Yes,Average

In [507]:
df[df.duplicated()]

Empty DataFrame
Columns: [Employee_ID, Name, Age, Gender, City, Department, Salary, Experience_Years, Joining_Date, Education, Employment_Type, Employment_Status, Product, Quantity, Sales_Amount, Discount_Percent, Remote_Work, Performance_Rating]
Index: []

# Employee ID

In [508]:
df[df['Employee_ID'].duplicated(keep=False)]

,Employee_ID,Name,Age,Gender,City,Department,Salary,Experience_Years,Joining_Date,Education,Employment_Type,Employment_Status,Product,Quantity,Sales_Amount,Discount_Percent,Remote_Work,Performance_Rating
5,EMP0006,Rahul Kapoor,24.0,Female,KOLKATA,IT,85043.0,3.0,2018-05-12 00:00:00,Post Graduate,Contract,Inactive,Keyboard,8,26028.0,29.0,Yes,Average
10,EMP0006,Rajiv Sethi,26.0,Male,Bangalore,Data Analytics,152399.0,18.0,2018-10-11 00:00:00,Post Graduate,Contract,Resigned,Phone,9,49597.0,12.0,No,Poor
49,EMP0050,Charles Taylor,25.0,Male,Bangalore,Finance,176262.0,19.0,2025-01-22 00:00:00,Diploma,Full-time,Inactive,Laptop,9,27374.0,38.0,Yes,Poor
50,EMP0050,Christopher Anderson,49.0,Female,Chennai,Sales,141056.0,20.0,2021-05-02 00:00:00,Graduate,Part-time,Inactive,Tablet,2,10392.0,15.0,Yes,Excellent

In [509]:
df = df[df['Employee_ID']!='EMP0006']

In [510]:
df.shape

(198, 18)

In [511]:
df = df[df['Employee_ID']!='EMP0050']

In [512]:
len(df['Employee_ID'].unique())

196

# Name

In [513]:
df[df['Name'].isnull()]

,Employee_ID,Name,Age,Gender,City,Department,Salary,Experience_Years,Joining_Date,Education,Employment_Type,Employment_Status,Product,Quantity,Sales_Amount,Discount_Percent,Remote_Work,Performance_Rating
128,EMP0129,NaN,22.0,Female,Bangalore,Customer Support,140615.0,7.0,2021-07-08 00:00:00,12th,Intern,Active,Keyboard,3,34092.0,13.0,No,Poor

In [514]:
df.dropna(subset=['Name'],inplace=True)

# Age

In [515]:
df['Age'].dtype

In [516]:
df['Age'].value_counts()

Age
36.0      10
55.0      10
26.0      10
28.0       8
56.0       8
35.0       8
53.0       8
42.0       7
50.0       7
31.0       7
57.0       7
27.0       7
24.0       6
49.0       6
44.0       5
37.0       5
47.0       5
46.0       5
25.0       4
33.0       4
22.0       4
40.0       4
51.0       4
52.0       4
48.0       4
38.0       4
30.0       3
32.0       3
45.0       3
23.0       3
41.0       3
39.0       3
29.0       2
58.0       2
43.0       2
54.0       2
34.0       2
thirty     1
5          1
92         1
Name: count, dtype: int64

In [517]:
df['Age'] = df['Age'].replace("thity","30.0")

In [518]:
df['Age'] = pd.to_numeric(df['Age'],errors='coerce')

In [519]:
df['Age'].isnull().sum()

4

In [520]:
df['Age'] = df['Age'].fillna(df['Age'].median())

In [521]:
df['Age'].isnull().sum()

0

# Gender

In [522]:
df['Gender'].value_counts()

Gender
Male      98
Female    91
M          1
F          1
male       1
female     1
?          1
Name: count, dtype: int64

In [523]:
df['Gender'] = df['Gender'].str.lower()

In [524]:
gender_map = {
    "male":"m",
    "female":"f",
    "?":"m"
}

In [525]:
df['Gender'] = df['Gender'].map(gender_map)

In [526]:
df['Gender'].value_counts()

Gender
m    100
f     92
Name: count, dtype: int64

In [527]:
df['Gender'].isnull().sum()

3

In [528]:
df['Gender'] = df['Gender'].ffill()

# City

In [529]:
df['City'].value_counts()

City
Mumbai       28
Jaipur       21
Chennai      21
Pune         20
Hyderabad    19
Delhi        18
Bangalore    18
Amritsar     15
Ahmedabad    14
Kolkata      13
MUMBAI        2
JAIPUR        2
BANGALORE     1
Name: count, dtype: int64

In [530]:
df['City'] = df['City'].str.lower().str.strip()

In [531]:
df['City'] = df['City'].fillna(df['City'].mode()[0])

In [532]:
df['City'].isnull().sum()

0

# Department

In [533]:
df['Department'] = df['Department'].str.lower().str.strip()

In [534]:
df['Department'].isnull().sum()

2

In [535]:
df['Department'] = df['Department'].fillna(df['Department'].mode()[0])

In [536]:
df.shape[0]

195

In [537]:
df[df['Department'].isnull()]

Empty DataFrame
Columns: [Employee_ID, Name, Age, Gender, City, Department, Salary, Experience_Years, Joining_Date, Education, Employment_Type, Employment_Status, Product, Quantity, Sales_Amount, Discount_Percent, Remote_Work, Performance_Rating]
Index: []

In [538]:
df['Department'].isnull().sum()

0

# Salary

In [539]:
df['Salary'] = pd.to_numeric(df['Salary'],errors='coerce')

In [540]:
df['Salary'].isnull().sum()

5

In [541]:
df['Salary'] = df['Salary'].fillna(df['Salary'].median())

In [542]:
df.columns

Index(['Employee_ID', 'Name', 'Age', 'Gender', 'City', 'Department', 'Salary',
       'Experience_Years', 'Joining_Date', 'Education', 'Employment_Type',
       'Employment_Status', 'Product', 'Quantity', 'Sales_Amount',
       'Discount_Percent', 'Remote_Work', 'Performance_Rating'],
      dtype='str')

# Experience Years

In [543]:
df['Experience_Years'].value_counts()

Experience_Years
12.0       13
16.0       13
8.0        13
5.0        12
3.0        12
10.0       12
15.0       12
20.0       12
14.0       11
18.0       10
9.0         9
19.0        8
13.0        8
11.0        8
4.0         8
1.0         8
2.0         8
6.0         8
17.0        6
7.0         2
5 years     1
Name: count, dtype: int64

In [544]:
df['Experience_Years'] = pd.to_numeric(df['Experience_Years'],errors='coerce')

In [545]:
df['Experience_Years'].value_counts()

Experience_Years
12.0    13
16.0    13
8.0     13
5.0     12
3.0     12
10.0    12
15.0    12
20.0    12
14.0    11
18.0    10
9.0      9
19.0     8
13.0     8
11.0     8
4.0      8
1.0      8
2.0      8
6.0      8
17.0     6
7.0      2
Name: count, dtype: int64

In [546]:
df['Experience_Years'] = df['Experience_Years'].fillna(df['Experience_Years'].median())

In [547]:
df.isnull().sum()

Employee_ID           0
Name                  0
Age                   0
Gender                0
City                  0
Department            0
Salary                0
Experience_Years      0
Joining_Date          1
Education             2
Employment_Type       1
Employment_Status     1
Product               1
Quantity              0
Sales_Amount          1
Discount_Percent      1
Remote_Work           2
Performance_Rating    1
dtype: int64

# Joining Date

In [552]:
df[df['Joining_Date'].isnull()]

Empty DataFrame
Columns: [Employee_ID, Name, Age, Gender, City, Department, Salary, Experience_Years, Joining_Date, Education, Employment_Type, Employment_Status, Product, Quantity, Sales_Amount, Discount_Percent, Remote_Work, Performance_Rating]
Index: []

In [551]:
df.dropna(subset=['Joining_Date'],inplace=True)

In [ ]:
df['Joining_Date'].value_counts()

Joining_Date
2025-05-05 00:00:00    3
2020-07-26 00:00:00    2
2021-06-20 00:00:00    2
2019-07-10 00:00:00    2
2023-07-26 00:00:00    2
                      ..
2025-03-08 00:00:00    1
2018-08-26 00:00:00    1
2021-11-21 00:00:00    1
2018-06-30 00:00:00    1
2026-01-29 00:00:00    1
Name: count, Length: 187, dtype: int64

In [556]:
df['Joining_Date'].dtype

dtype('<M8[us]')

In [555]:
df['Joining_Date'] = pd.to_datetime(df['Joining_Date'],errors='coerce')

In [560]:
df[df['Joining_Date'].isnull()]

Empty DataFrame
Columns: [Employee_ID, Name, Age, Gender, City, Department, Salary, Experience_Years, Joining_Date, Education, Employment_Type, Employment_Status, Product, Quantity, Sales_Amount, Discount_Percent, Remote_Work, Performance_Rating]
Index: []

In [559]:
df['Joining_Date'] = df['Joining_Date'].fillna(df['Joining_Date'].mode()[0])

In [561]:
df['Joining_Year'] = df['Joining_Date'].dt.year

In [562]:
df['Joining_month'] = df['Joining_Date'].dt.month

In [563]:
df['Joining_day'] = df['Joining_Date'].dt.day

In [567]:
df.head()

,Employee_ID,Name,Age,Gender,City,Department,Salary,Experience_Years,Education,Employment_Type,Employment_Status,Product,Quantity,Sales_Amount,Discount_Percent,Remote_Work,Performance_Rating,Joining_Year,Joining_month,Joining_day
0,EMP0001,Aarav Sharma,28.0,f,hyderabad,hr,31556.0,5.0,Graduate,Full-time,Resigned,Laptop,1,6240.0,13.0,Yes,Excellent,2026,4,26
1,EMP0002,Vivaan Verma,56.0,f,hyderabad,data analytics,77124.0,19.0,Diploma,Full-time,Inactive,Keyboard,7,22398.0,17.0,Yes,Good,2026,1,11
2,EMP0003,Aditya Singh,42.0,f,mumbai,operations,51793.0,12.0,High School,Contract,Active,Keyboard,8,35242.0,7.0,No,Excellent,2019,1,15
3,EMP0004,Arjun Mehta,40.0,f,amritsar,hr,101854.0,3.0,Graduate,Part-time,On Leave,Laptop,4,6719.0,24.0,No,Poor,2025,1,18
4,EMP0005,Rohan Gupta,44.0,f,hyderabad,it,67638.0,3.0,High School,Part-time,Inactive,Phone,8,24967.0,17.0,Yes,Average,2022,2,25

In [566]:
df.drop(columns=['Joining_Date'],inplace=True)

# Education

In [600]:
df['Education'] = df['Education'].str.lower().str.strip()

In [601]:
df['Education'].isnull().sum()

0

In [602]:
df['Education'] = df['Education'].fillna(df['Education'].mode()[0])

In [603]:
df['Education'].value_counts()

Education
12th             47
high school      38
post graduate    38
graduate         37
diploma          34
Name: count, dtype: int64

In [573]:
df.columns

Index(['Employee_ID', 'Name', 'Age', 'Gender', 'City', 'Department', 'Salary',
       'Experience_Years', 'Education', 'Employment_Type', 'Employment_Status',
       'Product', 'Quantity', 'Sales_Amount', 'Discount_Percent',
       'Remote_Work', 'Performance_Rating', 'Joining_Year', 'Joining_month',
       'Joining_day', 'Educatoin'],
      dtype='str')

# Employment Type

In [575]:
df['Employment_Type'] = df['Employment_Type'].str.lower().str.strip()

In [576]:
df['Employment_Type'].isnull().sum()

1

In [577]:
df['Employment_Type'] = df['Employment_Type'].fillna(df['Employment_Type'].mode()[0])

In [578]:
df['Employment_Type'].value_counts()

Employment_Type
part-time    56
contract     50
full-time    45
intern       43
Name: count, dtype: int64

# Employment Status

In [580]:
df['Employment_Status'] = df['Employment_Status'].str.lower().str.strip()

In [583]:
df['Employment_Status'].isnull().sum()

0

In [582]:
df['Employment_Status'] = df['Employment_Status'].fillna(df['Employment_Status'].mode()[0])

In [590]:
df['Employment_Status'].value_counts()

Employment_Status
resigned    54
on leave    49
active      46
inactive    45
Name: count, dtype: int64

# Product

In [592]:
df['Product'] = df['Product'].str.lower().str.strip()

In [593]:
df['Product'].isnull().sum()

0

In [594]:
df['Product'] = df['Product'].fillna(df['Product'].mode()[0])

In [608]:
df['Product'].value_counts()

Product
software license    36
laptop              31
keyboard            28
headphones          27
tablet              25
phone               24
monitor             23
Name: count, dtype: int64

In [607]:
df['Product'] = df['Product'].replace("not available",df['Product'].mode()[0])

# Quantity

In [610]:
df['Quantity'] = pd.to_numeric(df['Quantity'],errors='coerce')

In [613]:
df['Quantity'].isnull().sum()

0

In [612]:
df['Quantity'] = df['Quantity'].fillna(df['Quantity'].median())

In [614]:
df.head()

,Employee_ID,Name,Age,Gender,City,Department,Salary,Experience_Years,Education,Employment_Type,Employment_Status,Product,Quantity,Sales_Amount,Discount_Percent,Remote_Work,Performance_Rating,Joining_Year,Joining_month,Joining_day
0,EMP0001,Aarav Sharma,28.0,f,hyderabad,hr,31556.0,5.0,graduate,full-time,resigned,laptop,1.0,6240.0,13.0,Yes,Excellent,2026,4,26
1,EMP0002,Vivaan Verma,56.0,f,hyderabad,data analytics,77124.0,19.0,diploma,full-time,inactive,keyboard,7.0,22398.0,17.0,Yes,Good,2026,1,11
2,EMP0003,Aditya Singh,42.0,f,mumbai,operations,51793.0,12.0,high school,contract,active,keyboard,8.0,35242.0,7.0,No,Excellent,2019,1,15
3,EMP0004,Arjun Mehta,40.0,f,amritsar,hr,101854.0,3.0,graduate,part-time,on leave,laptop,4.0,6719.0,24.0,No,Poor,2025,1,18
4,EMP0005,Rohan Gupta,44.0,f,hyderabad,it,67638.0,3.0,high school,part-time,inactive,phone,8.0,24967.0,17.0,Yes,Average,2022,2,25

# Sales Amount

In [615]:
df['Sales_Amount'] = pd.to_numeric(df['Sales_Amount'],errors='coerce')

In [618]:
df['Sales_Amount'].isnull().sum()

0

In [617]:
df['Sales_Amount'] = df['Sales_Amount'].fillna(df['Sales_Amount'].median())

# Discount Percent

In [619]:
df['Discount_Percent'] = pd.to_numeric(df['Discount_Percent'],errors='coerce')

In [622]:
df['Discount_Percent'].isnull().sum()

0

In [621]:
df['Discount_Percent'] = df['Discount_Percent'].fillna(df['Discount_Percent'].median())

In [ ]:
df['Discount_Percent'] = df['Discount_Percent'].where(df['Discount_Percent']>=0,0)

# Remote Work

In [627]:
df['Remote_Work'] = df['Remote_Work'].str.strip().str.lower()

In [631]:
df['Remote_Work'].value_counts()

Remote_Work
no     113
yes     79
Name: count, dtype: int64

In [630]:
df['Remote_Work'] = df['Remote_Work'].replace({'y':"yes","n":"no"})

In [637]:
df['Remote_Work'].isnull().sum()

0

In [636]:
df['Remote_Work'] = df['Remote_Work'].fillna(df['Remote_Work'].mode()[0])

In [632]:
df.head()

,Employee_ID,Name,Age,Gender,City,Department,Salary,Experience_Years,Education,Employment_Type,Employment_Status,Product,Quantity,Sales_Amount,Discount_Percent,Remote_Work,Performance_Rating,Joining_Year,Joining_month,Joining_day
0,EMP0001,Aarav Sharma,28.0,f,hyderabad,hr,31556.0,5.0,graduate,full-time,resigned,laptop,1.0,6240.0,13.0,yes,Excellent,2026,4,26
1,EMP0002,Vivaan Verma,56.0,f,hyderabad,data analytics,77124.0,19.0,diploma,full-time,inactive,keyboard,7.0,22398.0,17.0,yes,Good,2026,1,11
2,EMP0003,Aditya Singh,42.0,f,mumbai,operations,51793.0,12.0,high school,contract,active,keyboard,8.0,35242.0,7.0,no,Excellent,2019,1,15
3,EMP0004,Arjun Mehta,40.0,f,amritsar,hr,101854.0,3.0,graduate,part-time,on leave,laptop,4.0,6719.0,24.0,no,Poor,2025,1,18
4,EMP0005,Rohan Gupta,44.0,f,hyderabad,it,67638.0,3.0,high school,part-time,inactive,phone,8.0,24967.0,17.0,yes,Average,2022,2,25

# Performance Rating

In [634]:
df['Performance_Rating'] = df['Performance_Rating'].str.strip().str.lower()

In [639]:
df['Performance_Rating'] = df['Performance_Rating'].replace("unknown",df['Performance_Rating'].mode()[0])

In [642]:
df['Performance_Rating'] = df['Performance_Rating'].fillna(df['Performance_Rating'].mode()[0])

In [644]:
df.isnull().sum()

Employee_ID           0
Name                  0
Age                   0
Gender                0
City                  0
Department            0
Salary                0
Experience_Years      0
Education             0
Employment_Type       0
Employment_Status     0
Product               0
Quantity              0
Sales_Amount          0
Discount_Percent      0
Remote_Work           0
Performance_Rating    0
Joining_Year          0
Joining_month         0
Joining_day           0
dtype: int64

In [645]:
df.head(20)

,Employee_ID,Name,Age,Gender,City,Department,Salary,Experience_Years,Education,Employment_Type,Employment_Status,Product,Quantity,Sales_Amount,Discount_Percent,Remote_Work,Performance_Rating,Joining_Year,Joining_month,Joining_day
0,EMP0001,Aarav Sharma,28.0,f,hyderabad,hr,31556.0,5.0,graduate,full-time,resigned,laptop,1.0,6240.0,13.0,yes,excellent,2026,4,26
1,EMP0002,Vivaan Verma,56.0,f,hyderabad,data analytics,77124.0,19.0,diploma,full-time,inactive,keyboard,7.0,22398.0,17.0,yes,good,2026,1,11
2,EMP0003,Aditya Singh,42.0,f,mumbai,operations,51793.0,12.0,high school,contract,active,keyboard,8.0,35242.0,7.0,no,excellent,2019,1,15
3,EMP0004,Arjun Mehta,40.0,f,amritsar,hr,101854.0,3.0,graduate,part-time,on leave,laptop,4.0,6719.0,24.0,no,poor,2025,1,18
4,EMP0005,Rohan Gupta,44.0,f,hyderabad,it,67638.0,3.0,high school,part-time,inactive,phone,8.0,24967.0,17.0,yes,average,2022,2,25
6,EMP0007,Karan Malhotra,29.0,f,amritsar,customer support,89651.0,19.0,12th,contract,inactive,phone,9.0,32443.0,5.0,yes,excellent,2026,5,10
7,EMP0008,Vikram Bhatia,30.0,f,mumbai,marketing,66938.0,13.0,12th,intern,on leave,headphones,1.0,44683.0,7.0,no,average,2025,8,19
8,EMP0009,Ankit Arora,28.0,f,jaipur,sales,101939.0,9.0,high school,part-time,active,software license,5.0,41974.0,32.0,yes,good,2022,11,16
9,EMP0010,Nikhil Khanna,44.0,m,amritsar,operations,67349.0,16.0,graduate,full-time,on leave,software license,5.0,15792.0,3.0,yes,excellent,2024,1,19
11,EMP0012,Siddharth Jain,44.0,f,mumbai,hr,139845.0,8.0,graduate,contract,active,headphones,9.0,15180.0,37.0,yes,excellent,2023,10,21
12,EMP0013,Manish Agarwal,25.0,m,delhi,operations,94798.5,3.0,high school,part-time,on leave,keyboard,8.0,14140.0,34.0,yes,poor,2020,7,26
13,EMP0014,Amit Tandon,36.0,m,mumbai,marketing,148987.0,14.0,diploma,intern,resigned,monitor,1.0,44229.0,6.0,yes,poor,2022,7,26
14,EMP0015,Varun Sood,42.0,m,hyderabad,data analytics,53644.0,5.0,12th,part-time,on leave,monitor,4.0,5040.0,28.0,yes,excellent,2020,10,15
15,EMP0016,Yash Chawla,55.0,m,mumbai,customer support,28868.0,16.0,12th,part-time,resigned,laptop,3.0,24936.0,0.0,no,average,2019,1,18
16,EMP0017,Mohit Bansal,50.0,f,bangalore,hr,99776.0,10.0,post graduate,full-time,active,keyboard,6.0,3846.0,3.0,no,good,2022,9,29
17,EMP0018,Akash Srivastava,24.0,m,mumbai,marketing,158124.0,8.0,12th,full-time,inactive,headphones,10.0,2704.0,39.0,yes,poor,2018,11,25
18,EMP0019,Harsh Vardhan,58.0,f,chennai,operations,173170.0,11.0,post graduate,contract,resigned,phone,5.0,30064.0,20.0,yes,excellent,2023,11,12
19,EMP0020,Abhishek Joshi,50.0,f,ahmedabad,hr,172585.0,17.0,diploma,part-time,on leave,laptop,4.0,24317.0,18.0,yes,poor,2019,2,14
20,EMP0021,Priya Sharma,55.0,m,ahmedabad,it,104303.0,4.0,post graduate,contract,active,laptop,9.0,10287.0,17.0,no,good,2024,11,10
21,EMP0022,Ananya Gupta,42.0,f,ahmedabad,data analytics,78371.0,9.0,graduate,full-time,resigned,software license,5.0,2989.0,0.0,no,good,2025,9,16

In [646]:
df.to_csv("clean_data.csv",index=False)