In [28]:
import pandas as pd

In [29]:
df = pd.read_csv("employee.csv")

In [30]:
df.head()

,Employee_ID,Name,Age,Gender,City,Department,Salary,Experience_Years,Education,Employment_Type,Employment_Status,Product,Quantity,Sales_Amount,Discount_Percent,Remote_Work,Performance_Rating,Joining_Year,Joining_month,Joining_day
0,EMP0001,Aarav Sharma,28.0,f,hyderabad,hr,31556.0,5.0,graduate,full-time,resigned,laptop,1.0,6240.0,13.0,yes,excellent,2026,4,26
1,EMP0002,Vivaan Verma,56.0,f,hyderabad,data analytics,77124.0,19.0,diploma,full-time,inactive,keyboard,7.0,22398.0,17.0,yes,good,2026,1,11
2,EMP0003,Aditya Singh,42.0,f,mumbai,operations,51793.0,12.0,high school,contract,active,keyboard,8.0,35242.0,7.0,no,excellent,2019,1,15
3,EMP0004,Arjun Mehta,40.0,f,amritsar,hr,101854.0,3.0,graduate,part-time,on leave,laptop,4.0,6719.0,24.0,no,poor,2025,1,18
4,EMP0005,Rohan Gupta,44.0,f,hyderabad,it,67638.0,3.0,high school,part-time,inactive,phone,8.0,24967.0,17.0,yes,average,2022,2,25

In [31]:
df.shape[0]

193

## Group by function

mean,sum,count,max,min

In [32]:
df.groupby('Gender')['Salary'].mean()

Gender
f    107476.801075
m     94636.220000
Name: Salary, dtype: float64

Salary Pool by department

In [43]:
df.groupby('Department',as_index=False)['Salary'].sum()

         Department     Salary
0  customer support  2616594.0
1    data analytics  1999026.0
2           finance  1140802.5
3                hr  2375384.0
4                it  2456293.5
5         marketing  2422328.0
6        operations  4234883.5
7             sales  2213653.0

## Group by with multiple aggregation

In [34]:
df.groupby('City')['Salary'].agg(['sum','mean','min','max'])

                 sum           mean      min       max
City
ahmedabad  1232485.0   88034.642857  41400.0  173281.0
amritsar   1701375.5  113425.033333  25701.0  176698.0
bangalore  1914437.0  100759.842105  36984.0  167352.0
chennai    1887212.0   89867.238095   5000.0  173170.0
delhi      1654302.0   91905.666667  36713.0  154861.0
hyderabad  1779751.0   93671.105263  25106.0  176023.0
jaipur     1794902.0   81586.454545  28215.0  158870.0
kolkata    2246584.0  172814.153846  28235.0  950000.0
mumbai     3226879.5  100839.984375  25284.0  174596.0
pune       2021036.5  101051.825000  29257.0  178879.0

## Grouping multiple columns

In [38]:
temp = df.groupby(['City','Gender','Employment_Type'],as_index=False)['Salary'].mean()

In [40]:
temp.head(30)

         City Gender Employment_Type         Salary
0   ahmedabad      f        contract  173281.000000
1   ahmedabad      f       full-time   72864.000000
2   ahmedabad      f          intern   77637.000000
3   ahmedabad      f       part-time  108894.000000
4   ahmedabad      m        contract  104303.000000
5   ahmedabad      m       full-time   80497.000000
6   ahmedabad      m          intern   77376.000000
7   ahmedabad      m       part-time   57192.000000
8    amritsar      f        contract  139658.750000
9    amritsar      f       full-time  176698.000000
10   amritsar      f          intern   90082.000000
11   amritsar      f       part-time   94644.750000
12   amritsar      m        contract  124932.166667
13   amritsar      m       full-time   67349.000000
14   amritsar      m          intern   55236.000000
15  bangalore      f        contract  105990.800000
16  bangalore      f       full-time  115200.333333
17  bangalore      f          intern   77652.000000
18  bangalore      f       part-time  102659.000000
19  bangalore      m        contract   84870.000000
20  bangalore      m       full-time  117018.000000
21  bangalore      m          intern   44304.000000
22  bangalore      m       part-time  146300.333333
23    chennai      f        contract  173170.000000
24    chennai      f       full-time   66326.750000
25    chennai      f          intern  164893.000000
26    chennai      f       part-time   87173.500000
27    chennai      m        contract   80026.400000
28    chennai      m       full-time  112645.333333
29    chennai      m          intern   72766.333333

In [49]:
df.groupby(['Gender','City'])[['Salary','Age']].sum()

                     Salary    Age
Gender City
f      ahmedabad   614434.0  268.0
       amritsar   1203994.0  369.0
       bangalore  1055866.0  367.0
       chennai     777717.0  347.0
       delhi       715243.0  303.0
       hyderabad   955311.0  367.0
       jaipur      597931.0  262.0
       kolkata    1193236.0  237.0
       mumbai     1527749.5  547.0
       pune       1353861.0  533.0
m      ahmedabad   618051.0  349.0
       amritsar    497381.5  160.0
       bangalore   858571.0  368.0
       chennai    1109495.0  555.0
       delhi       939059.0  385.0
       hyderabad   824440.0  424.0
       jaipur     1196971.0  630.0
       kolkata    1053348.0  312.0
       mumbai     1699130.0  696.0
       pune        667175.5  291.0

## Custom function with group by

In [50]:
df.groupby('Department')['Salary'].apply(lambda x:x.max()-x.min())

Department
customer support    151592.0
data analytics      173879.0
finance             116687.0
hr                  146209.0
it                  136966.0
marketing           151374.0
operations          924716.0
sales               153411.0
Name: Salary, dtype: float64

In [52]:
df1 = df

In [54]:
df1['temp'] = df1.groupby('Department')['Salary'].transform('mean')

In [57]:
df1[['Department','temp']].head(10)

         Department           temp
0                hr   98974.333333
1    data analytics   90864.818182
2        operations  124555.397059
3                hr   98974.333333
4                it  111649.704545
5  customer support   90227.379310
6         marketing  100930.333333
7             sales   92235.541667
8        operations  124555.397059
9                hr   98974.333333

In [58]:
df.head()

,Employee_ID,Name,Age,Gender,City,Department,Salary,Experience_Years,Education,Employment_Type,...,Product,Quantity,Sales_Amount,Discount_Percent,Remote_Work,Performance_Rating,Joining_Year,Joining_month,Joining_day,temp
0,EMP0001,Aarav Sharma,28.0,f,hyderabad,hr,31556.0,5.0,graduate,full-time,...,laptop,1.0,6240.0,13.0,yes,excellent,2026,4,26,98974.333333
1,EMP0002,Vivaan Verma,56.0,f,hyderabad,data analytics,77124.0,19.0,diploma,full-time,...,keyboard,7.0,22398.0,17.0,yes,good,2026,1,11,90864.818182
2,EMP0003,Aditya Singh,42.0,f,mumbai,operations,51793.0,12.0,high school,contract,...,keyboard,8.0,35242.0,7.0,no,excellent,2019,1,15,124555.397059
3,EMP0004,Arjun Mehta,40.0,f,amritsar,hr,101854.0,3.0,graduate,part-time,...,laptop,4.0,6719.0,24.0,no,poor,2025,1,18,98974.333333
4,EMP0005,Rohan Gupta,44.0,f,hyderabad,it,67638.0,3.0,high school,part-time,...,phone,8.0,24967.0,17.0,yes,average,2022,2,25,111649.704545

In [59]:
df.drop(columns='temp',inplace=True)

In [60]:
df.groupby('Department').size()

Department
customer support    29
data analytics      22
finance             14
hr                  24
it                  22
marketing           24
operations          34
sales               24
dtype: int64

In [61]:
df.groupby('Gender').size()

Gender
f     93
m    100
dtype: int64

# Pivot table

In [62]:
pd.pivot_table(df,
               'Salary',
               'Department',
               aggfunc='mean')

                         Salary
Department
customer support   90227.379310
data analytics     90864.818182
finance            81485.892857
hr                 98974.333333
it                111649.704545
marketing         100930.333333
operations        124555.397059
sales              92235.541667

In [67]:
pd.pivot_table(df,
               'Salary',
               index='Department',
               columns='Gender',
               aggfunc='mean')

Gender                        f              m
Department
customer support   95985.000000   83141.076923
data analytics     82915.818182   98813.818182
finance            84165.785714   78806.000000
hr                111898.785714   80880.100000
it                109832.333333  113830.550000
marketing          91086.727273  109259.538462
operations        160580.923077  102253.880952
sales             109363.444444   81958.800000

In [73]:
pd.pivot_table(df,
               values=['Salary','Age'],
               index='City',
               columns=['Gender'],
               aggfunc=['mean','min','max'],
               )

                mean                                            min        \
                 Age                    Salary                  Age
Gender             f          m              f              m     f     m
City
ahmedabad  44.666667  43.625000  102405.666667   77256.375000  32.0  28.0
amritsar   36.900000  32.000000  120399.400000   99476.300000  26.0   5.0
bangalore  36.700000  40.888889  105586.600000   95396.777778  26.0  31.0
chennai    43.375000  42.692308   97214.625000   85345.769231  26.0  22.0
delhi      37.875000  38.500000   89405.375000   93905.900000  24.0  25.0
hyderabad  36.700000  47.111111   95531.100000   91604.444444  22.0  34.0
jaipur     32.750000  45.000000   74741.375000   85497.928571  23.0  27.0
kolkata    47.400000  39.000000  238647.200000  131668.500000  39.0  25.0
mumbai     36.466667  40.941176  101849.966667   99948.823529  26.0  24.0
pune       41.000000  41.571429  104143.153846   95310.785714  23.0  26.0

                              max
            Salary            Age          Salary
Gender           f        m     f     m         f         m
City
ahmedabad  45203.0  41400.0  57.0  57.0  173281.0  133575.0
amritsar   25701.0  55236.0  53.0  53.0  176698.0  144860.0
bangalore  44269.0  36984.0  56.0  56.0  155131.0  167352.0
chennai     5000.0  26376.0  58.0  58.0  173170.0  149701.0
delhi      37043.0  36713.0  55.0  55.0  151669.0  154861.0
hyderabad  31556.0  25106.0  56.0  56.0  176023.0  166824.0
jaipur     28215.0  31793.0  52.0  92.0  133955.0  158870.0
kolkata    28235.0  50478.0  56.0  57.0  950000.0  179609.0
mumbai     25284.0  27661.0  55.0  57.0  164655.0  174596.0
pune       44671.0  29257.0  54.0  55.0  178879.0  177761.0

In [77]:
pd.pivot_table(df,
               values=['Salary'],
               index='City',
               columns=['Gender'],
               aggfunc=['sum'],
               margins=True
               )

                 sum
              Salary
Gender             f          m         All
City
ahmedabad   614434.0   618051.0   1232485.0
amritsar   1203994.0   497381.5   1701375.5
bangalore  1055866.0   858571.0   1914437.0
chennai     777717.0  1109495.0   1887212.0
delhi       715243.0   939059.0   1654302.0
hyderabad   955311.0   824440.0   1779751.0
jaipur      597931.0  1196971.0   1794902.0
kolkata    1193236.0  1053348.0   2246584.0
mumbai     1527749.5  1699130.0   3226879.5
pune       1353861.0   667175.5   2021036.5
All        9995342.5  9463622.0  19458964.5

# Cross tab

In [78]:
pd.crosstab(df['Gender'],df['Department'])

Department,customer support,data analytics,finance,hr,it,marketing,operations,sales
Gender,,,,,,,,
f,16,11,7,14,12,11,13,9
m,13,11,7,10,10,13,21,15

In [80]:
pd.crosstab(df['Gender'],df['Department'],margins=True)

Department,customer support,data analytics,finance,hr,it,marketing,operations,sales,All
Gender,,,,,,,,,
f,16,11,7,14,12,11,13,9,93
m,13,11,7,10,10,13,21,15,100
All,29,22,14,24,22,24,34,24,193

In [86]:
pd.crosstab(df['City'],df['Department'],margins=True,normalize='columns')

Department,customer support,data analytics,finance,hr,it,marketing,operations,sales,All
City,,,,,,,,,
ahmedabad,0.068966,0.045455,0.071429,0.041667,0.136364,0.083333,0.058824,0.083333,0.072539
amritsar,0.103448,0.090909,0.000000,0.125000,0.090909,0.041667,0.088235,0.041667,0.077720
bangalore,0.206897,0.090909,0.071429,0.083333,0.090909,0.041667,0.088235,0.083333,0.098446
chennai,0.034483,0.181818,0.071429,0.041667,0.045455,0.208333,0.147059,0.125000,0.108808
delhi,0.103448,0.045455,0.000000,0.083333,0.136364,0.083333,0.147059,0.083333,0.093264
hyderabad,0.103448,0.136364,0.071429,0.166667,0.136364,0.041667,0.058824,0.083333,0.098446
jaipur,0.068966,0.136364,0.214286,0.083333,0.090909,0.041667,0.117647,0.208333,0.113990
kolkata,0.034483,0.090909,0.000000,0.041667,0.090909,0.125000,0.058824,0.083333,0.067358
mumbai,0.206897,0.045455,0.285714,0.208333,0.045455,0.250000,0.205882,0.083333,0.165803
pune,0.068966,0.136364,0.214286,0.125000,0.136364,0.083333,0.029412,0.125000,0.103627

# sort_values, sort_index

In [87]:
df.head()

,Employee_ID,Name,Age,Gender,City,Department,Salary,Experience_Years,Education,Employment_Type,Employment_Status,Product,Quantity,Sales_Amount,Discount_Percent,Remote_Work,Performance_Rating,Joining_Year,Joining_month,Joining_day
0,EMP0001,Aarav Sharma,28.0,f,hyderabad,hr,31556.0,5.0,graduate,full-time,resigned,laptop,1.0,6240.0,13.0,yes,excellent,2026,4,26
1,EMP0002,Vivaan Verma,56.0,f,hyderabad,data analytics,77124.0,19.0,diploma,full-time,inactive,keyboard,7.0,22398.0,17.0,yes,good,2026,1,11
2,EMP0003,Aditya Singh,42.0,f,mumbai,operations,51793.0,12.0,high school,contract,active,keyboard,8.0,35242.0,7.0,no,excellent,2019,1,15
3,EMP0004,Arjun Mehta,40.0,f,amritsar,hr,101854.0,3.0,graduate,part-time,on leave,laptop,4.0,6719.0,24.0,no,poor,2025,1,18
4,EMP0005,Rohan Gupta,44.0,f,hyderabad,it,67638.0,3.0,high school,part-time,inactive,phone,8.0,24967.0,17.0,yes,average,2022,2,25

In [ ]:
df.sort_index(ascending=False)

,Employee_ID,Name,Age,Gender,City,Department,Salary,Experience_Years,Education,Employment_Type,Employment_Status,Product,Quantity,Sales_Amount,Discount_Percent,Remote_Work,Performance_Rating,Joining_Year,Joining_month,Joining_day
192,EMP0200,Taylor Hall,36.0,f,chennai,marketing,134119.0,19.0,diploma,full-time,active,phone,4.0,33901.0,2.0,no,excellent,2026,1,29
191,EMP0199,Madison Walker,53.0,m,hyderabad,sales,25673.0,16.0,diploma,intern,inactive,phone,1.0,36332.0,26.0,yes,average,2018,6,30
190,EMP0198,Mackenzie Lewis,57.0,f,ahmedabad,operations,45203.0,2.0,12th,part-time,on leave,phone,5.0,6843.0,36.0,yes,good,2023,7,26
189,EMP0197,Kayla Clark,31.0,f,bangalore,operations,155131.0,5.0,diploma,full-time,active,tablet,7.0,17924.0,33.0,yes,average,2021,11,21
188,EMP0196,Brittany Robinson,48.0,m,mumbai,customer support,87557.0,4.0,12th,full-time,on leave,keyboard,3.0,7927.0,0.0,yes,excellent,2018,8,26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,EMP0005,Rohan Gupta,44.0,f,hyderabad,it,67638.0,3.0,high school,part-time,inactive,phone,8.0,24967.0,17.0,yes,average,2022,2,25
3,EMP0004,Arjun Mehta,40.0,f,amritsar,hr,101854.0,3.0,graduate,part-time,on leave,laptop,4.0,6719.0,24.0,no,poor,2025,1,18
2,EMP0003,Aditya Singh,42.0,f,mumbai,operations,51793.0,12.0,high school,contract,active,keyboard,8.0,35242.0,7.0,no,excellent,2019,1,15
1,EMP0002,Vivaan Verma,56.0,f,hyderabad,data analytics,77124.0,19.0,diploma,full-time,inactive,keyboard,7.0,22398.0,17.0,yes,good,2026,1,11
0,EMP0001,Aarav Sharma,28.0,f,hyderabad,hr,31556.0,5.0,graduate,full-time,resigned,laptop,1.0,6240.0,13.0,yes,excellent,2026,4,26

In [104]:
df[['Name','Age','Salary']].sort_values(['Age','Salary'],ascending=[True,False]).head(20)

                  Name   Age    Salary
32   Muskan Srivastava   5.0  135138.0
154     Juan Rodriguez  22.0   96651.0
24         Pooja Arora  22.0   55236.0
49       Steven Harris  22.0   48940.0
112        Lucy Cooper  22.0   46292.0
67         Grace White  23.0  122132.0
58      Isabella Jones  23.0  110032.0
119         Arun Kumar  23.0   35201.0
15    Akash Srivastava  24.0  158124.0
148      Bilal Hussain  24.0  151669.0
86         Henry Green  24.0  121662.0
52        Kevin Garcia  24.0   78361.0
104     Lillian Rogers  24.0   44671.0
179    Lauren Anderson  24.0   37043.0
178       Megan Taylor  25.0  165096.0
10      Manish Agarwal  25.0   94798.5
182       Nicole White  25.0   85017.0
72       Lily Martinez  25.0   46178.0
89         Jack Nelson  26.0  177761.0
151      Adnan Qureshi  26.0  156034.0

In [95]:
df['Salary'].sort_values(ascending=False)

140    950000.0
47     179609.0
110    179084.0
169    178879.0
89     177761.0
         ...
46      25701.0
191     25673.0
181     25284.0
27      25106.0
103      5000.0
Name: Salary, Length: 193, dtype: float64

In [97]:
df['Salary'].sort_values(ascending=False).sort_index()

0       31556.0
1       77124.0
2       51793.0
3      101854.0
4       67638.0
         ...
188     87557.0
189    155131.0
190     45203.0
191     25673.0
192    134119.0
Name: Salary, Length: 193, dtype: float64

In [107]:
df.sort_values('Salary',ascending=False).head(5)

,Employee_ID,Name,Age,Gender,City,Department,Salary,Experience_Years,Education,Employment_Type,Employment_Status,Product,Quantity,Sales_Amount,Discount_Percent,Remote_Work,Performance_Rating,Joining_Year,Joining_month,Joining_day
140,EMP0148,Aaliya Khan,56.0,f,kolkata,operations,950000.0,14.0,12th,part-time,on leave,monitor,3.0,49541.0,34.0,no,good,2018,7,12
47,EMP0053,Anthony Jackson,37.0,m,kolkata,marketing,179609.0,18.0,post graduate,part-time,on leave,software license,3.0,4779.0,3.0,yes,average,2025,6,1
110,EMP0117,Zoe Bailey,56.0,m,kolkata,sales,179084.0,4.0,high school,part-time,resigned,phone,3.0,21245.0,14.0,no,average,2020,1,16
169,EMP0177,Gabriela Diaz,46.0,f,pune,data analytics,178879.0,20.0,post graduate,contract,active,keyboard,3.0,20624.0,7.0,yes,average,2019,4,13
89,EMP0096,Jack Nelson,26.0,m,pune,it,177761.0,13.0,post graduate,full-time,on leave,headphones,7.0,42271.0,21.0,yes,excellent,2025,6,11

# nlargest, nsmallest

In [106]:
df.nlargest(5,'Salary')

,Employee_ID,Name,Age,Gender,City,Department,Salary,Experience_Years,Education,Employment_Type,Employment_Status,Product,Quantity,Sales_Amount,Discount_Percent,Remote_Work,Performance_Rating,Joining_Year,Joining_month,Joining_day
140,EMP0148,Aaliya Khan,56.0,f,kolkata,operations,950000.0,14.0,12th,part-time,on leave,monitor,3.0,49541.0,34.0,no,good,2018,7,12
47,EMP0053,Anthony Jackson,37.0,m,kolkata,marketing,179609.0,18.0,post graduate,part-time,on leave,software license,3.0,4779.0,3.0,yes,average,2025,6,1
110,EMP0117,Zoe Bailey,56.0,m,kolkata,sales,179084.0,4.0,high school,part-time,resigned,phone,3.0,21245.0,14.0,no,average,2020,1,16
169,EMP0177,Gabriela Diaz,46.0,f,pune,data analytics,178879.0,20.0,post graduate,contract,active,keyboard,3.0,20624.0,7.0,yes,average,2019,4,13
89,EMP0096,Jack Nelson,26.0,m,pune,it,177761.0,13.0,post graduate,full-time,on leave,headphones,7.0,42271.0,21.0,yes,excellent,2025,6,11

In [109]:
df[['Name','Salary']].nsmallest(5,'Salary')

                Name   Salary
103    Violet Morris   5000.0
27       Shreya Jain  25106.0
181  Rebecca Jackson  25284.0
191   Madison Walker  25673.0
46    Matthew Thomas  25701.0