In [1]:
import numpy as np

In [2]:
np.random.seed(42)
subjects = ["English","hindi","Math","Physics","Chemistry"]
students = [f"Student {i + 1}" for i in range(20)]
marks = np.random.randint(1,100,size=(20,5))

In [3]:
marks

array([[52, 93, 15, 72, 61],
       [21, 83, 87, 75, 75],
       [88, 24,  3, 22, 53],
       [ 2, 88, 30, 38,  2],
       [64, 60, 21, 33, 76],
       [58, 22, 89, 49, 91],
       [59, 42, 92, 60, 80],
       [15, 62, 62, 47, 62],
       [51, 55, 64,  3, 51],
       [ 7, 21, 73, 39, 18],
       [ 4, 89, 60, 14,  9],
       [90, 53,  2, 84, 92],
       [60, 71, 44,  8, 47],
       [35, 78, 81, 36, 50],
       [ 4,  2,  6, 54,  4],
       [54, 93, 63, 18, 90],
       [44, 34, 74, 62, 14],
       [95, 48, 15, 72, 78],
       [87, 62, 40, 85, 80],
       [82, 53, 24, 26, 89]])

In [10]:
print(f"Total Students: {marks.shape[0]}")
print(f"Total Subjects: {marks.shape[1]}")

Total Students: 20
Total Subjects: 5

total Marks of students

In [7]:
total_marks = np.sum(marks,axis=1)
print(total_marks)

[293 341 190 160 254 309 333 248 224 158 176 321 230 280  70 318 228 308
 354 274]

In [9]:
percentages = total_marks/500 * 100
print(percentages)

[58.6 68.2 38.  32.  50.8 61.8 66.6 49.6 44.8 31.6 35.2 64.2 46.  56.
 14.  63.6 45.6 61.6 70.8 54.8]

In [13]:
topper_idx = np.argmax(total_marks)
print(f"Topper Student{topper_idx + 1} with {total_marks[topper_idx]}" )

Topper Student19 with 354

Top 3 students

In [26]:
top_3_students = np.argsort(total_marks)[-3:][::-1]

for i,idx in enumerate(top_3_students,1):
    print(f"{i}. Student{idx} with {total_marks[idx]}")

1. Student18 with 354
2. Student1 with 341
3. Student6 with 333

Average subjects marks

In [ ]:
avg_marks = marks.mean(axis=0)

for subject,m in zip(subjects,avg_marks):
    print(f"{subject} : {m}")

[48.6  56.65 47.25 44.85 56.1 ]
English : 48.6
hindi : 56.65
Math : 47.25
Physics : 44.85
Chemistry : 56.1

In [29]:
import pandas as pd

In [31]:
df = pd.DataFrame(marks,index=students,columns=subjects)

In [33]:
df['Total'] = df.sum(axis=1)

In [35]:
df['pecentage'] = df['Total']/500 * 100

In [36]:
df

            English  hindi  Math  Physics  Chemistry  Total  pecentage
Student 1        52     93    15       72         61    293       58.6
Student 2        21     83    87       75         75    341       68.2
Student 3        88     24     3       22         53    190       38.0
Student 4         2     88    30       38          2    160       32.0
Student 5        64     60    21       33         76    254       50.8
Student 6        58     22    89       49         91    309       61.8
Student 7        59     42    92       60         80    333       66.6
Student 8        15     62    62       47         62    248       49.6
Student 9        51     55    64        3         51    224       44.8
Student 10        7     21    73       39         18    158       31.6
Student 11        4     89    60       14          9    176       35.2
Student 12       90     53     2       84         92    321       64.2
Student 13       60     71    44        8         47    230       46.0
Student 14       35     78    81       36         50    280       56.0
Student 15        4      2     6       54          4     70       14.0
Student 16       54     93    63       18         90    318       63.6
Student 17       44     34    74       62         14    228       45.6
Student 18       95     48    15       72         78    308       61.6
Student 19       87     62    40       85         80    354       70.8
Student 20       82     53    24       26         89    274       54.8

In [38]:
df.describe()

,English,hindi,Math,Physics,Chemistry,Total,pecentage
count,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000
mean,48.600000,56.650000,47.250000,44.850000,56.100000,253.450000,50.690000
std,31.285443,26.608813,30.890085,25.252983,31.129441,74.411003,14.882201
min,2.000000,2.000000,2.000000,3.000000,2.000000,70.000000,14.000000
25%,19.500000,40.000000,19.500000,25.000000,39.750000,215.500000,43.100000
50%,53.000000,57.500000,52.000000,43.000000,61.500000,264.000000,52.800000
75%,68.500000,79.250000,73.250000,64.500000,80.000000,311.250000,62.250000
max,95.000000,93.000000,92.000000,85.000000,92.000000,354.000000,70.800000