In [16]:
import pandas as pd

In [17]:
df1 = pd.read_csv("employee_data.txt",sep=';')
df2 = pd.read_csv("employee_data.txt",sep=';')

In [18]:
df1.head()

,Employee_ID,Name,Age,Department,City,Salary,Experience_Years,Performance_Rating
0,EMP0001,Simran Sharma,34,Sales,Delhi,57013,6.9,4
1,EMP0002,Ananya Agarwal,46,Finance,Delhi,98245,7.4,1
2,EMP0003,Vikram Bansal,32,Data Science,Jaipur,48178,9.0,4
3,EMP0004,Kavya Gupta,47,IT,Hyderabad,89877,2.6,3
4,EMP0005,Isha Patel,35,Operations,Pune,87625,9.2,1

In [19]:
df1.shape

(100, 8)

In [20]:
df2.head()

,Employee_ID,Name,Age,Department,City,Salary,Experience_Years,Performance_Rating
0,EMP0001,Simran Sharma,34,Sales,Delhi,57013,6.9,4
1,EMP0002,Ananya Agarwal,46,Finance,Delhi,98245,7.4,1
2,EMP0003,Vikram Bansal,32,Data Science,Jaipur,48178,9.0,4
3,EMP0004,Kavya Gupta,47,IT,Hyderabad,89877,2.6,3
4,EMP0005,Isha Patel,35,Operations,Pune,87625,9.2,1

In [21]:
df2.set_index((f"emp{i}" for i in range(1,101)),inplace=True)

In [22]:
df2.head()

,Employee_ID,Name,Age,Department,City,Salary,Experience_Years,Performance_Rating
emp1,EMP0001,Simran Sharma,34,Sales,Delhi,57013,6.9,4
emp2,EMP0002,Ananya Agarwal,46,Finance,Delhi,98245,7.4,1
emp3,EMP0003,Vikram Bansal,32,Data Science,Jaipur,48178,9.0,4
emp4,EMP0004,Kavya Gupta,47,IT,Hyderabad,89877,2.6,3
emp5,EMP0005,Isha Patel,35,Operations,Pune,87625,9.2,1

# Column Selection

In [ ]:
df1['Salary']

76497.52

In [31]:
df1[['Name','Age','Salary']].head()

             Name  Age  Salary
0   Simran Sharma   34   57013
1  Ananya Agarwal   46   98245
2   Vikram Bansal   32   48178
3     Kavya Gupta   47   89877
4      Isha Patel   35   87625

# Row Selection

iloc, loc

In [35]:
df2.head()

,Employee_ID,Name,Age,Department,City,Salary,Experience_Years,Performance_Rating
emp1,EMP0001,Simran Sharma,34,Sales,Delhi,57013,6.9,4
emp2,EMP0002,Ananya Agarwal,46,Finance,Delhi,98245,7.4,1
emp3,EMP0003,Vikram Bansal,32,Data Science,Jaipur,48178,9.0,4
emp4,EMP0004,Kavya Gupta,47,IT,Hyderabad,89877,2.6,3
emp5,EMP0005,Isha Patel,35,Operations,Pune,87625,9.2,1

In [39]:
#using the label to select the record
df2.loc['emp1']

Employee_ID                 EMP0001
Name                  Simran Sharma
Age                              34
Department                    Sales
City                          Delhi
Salary                        57013
Experience_Years                6.9
Performance_Rating                4
Name: emp1, dtype: object

In [38]:
df2.iloc[0]

Employee_ID                 EMP0001
Name                  Simran Sharma
Age                              34
Department                    Sales
City                          Delhi
Salary                        57013
Experience_Years                6.9
Performance_Rating                4
Name: emp1, dtype: object

# Row + Column

In [40]:
df2.head()

,Employee_ID,Name,Age,Department,City,Salary,Experience_Years,Performance_Rating
emp1,EMP0001,Simran Sharma,34,Sales,Delhi,57013,6.9,4
emp2,EMP0002,Ananya Agarwal,46,Finance,Delhi,98245,7.4,1
emp3,EMP0003,Vikram Bansal,32,Data Science,Jaipur,48178,9.0,4
emp4,EMP0004,Kavya Gupta,47,IT,Hyderabad,89877,2.6,3
emp5,EMP0005,Isha Patel,35,Operations,Pune,87625,9.2,1

In [41]:
df2.loc['emp1','Name']

'Simran Sharma'

In [43]:
df2.iloc[2,3]

'Data Science'

# Slicing

In [47]:
df1.head(10)

,Employee_ID,Name,Age,Department,City,Salary,Experience_Years,Performance_Rating
0,EMP0001,Simran Sharma,34,Sales,Delhi,57013,6.9,4
1,EMP0002,Ananya Agarwal,46,Finance,Delhi,98245,7.4,1
2,EMP0003,Vikram Bansal,32,Data Science,Jaipur,48178,9.0,4
3,EMP0004,Kavya Gupta,47,IT,Hyderabad,89877,2.6,3
4,EMP0005,Isha Patel,35,Operations,Pune,87625,9.2,1
5,EMP0006,Simran Sharma,28,Finance,Pune,69696,8.0,2
6,EMP0007,Sneha Agarwal,38,Sales,Jaipur,91600,1.0,5
7,EMP0008,Sneha Mishra,37,Finance,Pune,84115,3.6,1
8,EMP0009,Pooja Gupta,47,HR,Mumbai,99924,13.9,1
9,EMP0010,Rohan Kapoor,39,Marketing,Bengaluru,44800,14.5,1

In [53]:
df1.iloc[5:21,4:7]

          City  Salary  Experience_Years
5         Pune   69696               8.0
6       Jaipur   91600               1.0
7         Pune   84115               3.6
8       Mumbai   99924              13.9
9    Bengaluru   44800              14.5
10  Chandigarh   86784              14.6
11   Bengaluru   45660               4.0
12   Bengaluru   53080               7.2
13       Delhi   73470              13.5
14   Bengaluru   81195              13.8
15     Kolkata  108919               7.5
16   Bengaluru   85107               8.1
17   Bengaluru  103232               6.6
18      Mumbai   36628               5.2
19     Kolkata   48258               6.9
20   Hyderabad   90063               6.3

In [63]:
df2.loc['emp10':'emp20','Name':'Salary']

                 Name  Age    Department        City  Salary
emp10    Rohan Kapoor   39     Marketing   Bengaluru   44800
emp11     Meera Patel   46       Finance  Chandigarh   86784
emp12  Vikram Agarwal   29       Finance   Bengaluru   45660
emp13   Rahul Agarwal   41    Operations   Bengaluru   53080
emp14    Sneha Kapoor   28  Data Science       Delhi   73470
emp15    Aditya Gupta   35         Sales   Bengaluru   81195
emp16   Vikram Bansal   37     Marketing     Kolkata  108919
emp17   Pooja Agarwal   35         Sales   Bengaluru   85107
emp18     Riya Kapoor   36            IT   Bengaluru  103232
emp19   Vivaan Mishra   21         Sales      Mumbai   36628
emp20      Arjun Shah   35    Operations     Kolkata   48258

# Boolean Filtering

In [64]:
df1.head()

,Employee_ID,Name,Age,Department,City,Salary,Experience_Years,Performance_Rating
0,EMP0001,Simran Sharma,34,Sales,Delhi,57013,6.9,4
1,EMP0002,Ananya Agarwal,46,Finance,Delhi,98245,7.4,1
2,EMP0003,Vikram Bansal,32,Data Science,Jaipur,48178,9.0,4
3,EMP0004,Kavya Gupta,47,IT,Hyderabad,89877,2.6,3
4,EMP0005,Isha Patel,35,Operations,Pune,87625,9.2,1

In [67]:
# select the employees with age > 40

df1[df1['Age']>40]

,Employee_ID,Name,Age,Department,City,Salary,Experience_Years,Performance_Rating
1,EMP0002,Ananya Agarwal,46,Finance,Delhi,98245,7.4,1
3,EMP0004,Kavya Gupta,47,IT,Hyderabad,89877,2.6,3
8,EMP0009,Pooja Gupta,47,HR,Mumbai,99924,13.9,1
10,EMP0011,Meera Patel,46,Finance,Chandigarh,86784,14.6,4
12,EMP0013,Rahul Agarwal,41,Operations,Bengaluru,53080,7.2,3
21,EMP0022,Aditi Patel,44,Finance,Chandigarh,111148,0.5,2
22,EMP0023,Simran Shah,47,IT,Kolkata,33264,12.1,3
23,EMP0024,Kavya Mishra,48,Finance,Hyderabad,41671,0.7,5
30,EMP0031,Priya Joshi,43,Marketing,Kolkata,96522,13.6,4
33,EMP0034,Nisha Kapoor,44,HR,Mumbai,108057,12.7,3
37,EMP0038,Meera Reddy,46,Operations,Delhi,81443,3.0,5
38,EMP0039,Karan Malhotra,50,Operations,Chandigarh,36246,9.9,5
42,EMP0043,Vivaan Patel,50,Operations,Kolkata,91709,9.1,4
47,EMP0048,Simran Mehta,47,Finance,Hyderabad,35605,5.9,4
48,EMP0049,Aditya Mehta,45,Finance,Kolkata,51339,2.5,4
50,EMP0051,Aditi Agarwal,49,IT,Jaipur,42359,5.9,1
52,EMP0053,Isha Mishra,50,HR,Kolkata,109669,3.7,3
54,EMP0055,Arjun Shah,49,Sales,Pune,67659,5.3,2
56,EMP0057,Aarav Agarwal,47,Sales,Chandigarh,53355,10.9,3
58,EMP0059,Karan Singh,49,Finance,Jaipur,110570,8.2,5
60,EMP0061,Vivaan Agarwal,45,Operations,Bengaluru,46336,10.4,1
65,EMP0066,Ananya Verma,50,HR,Hyderabad,48453,11.5,5
66,EMP0067,Arjun Gupta,43,HR,Chandigarh,30459,8.6,5
70,EMP0071,Rahul Reddy,41,Finance,Delhi,82795,9.1,4
73,EMP0074,Simran Chopra,48,HR,Jaipur,49562,13.4,3
78,EMP0079,Neha Malhotra,43,HR,Pune,119238,14.3,2
84,EMP0085,Aarav Mehta,42,Marketing,Delhi,83283,10.7,4
85,EMP0086,Rahul Mishra,47,Data Science,Jaipur,86309,14.9,1
86,EMP0087,Meera Patel,49,Operations,Mumbai,79640,8.0,1
87,EMP0088,Aditi Mishra,44,HR,Hyderabad,104801,7.2,1
88,EMP0089,Kavya Verma,45,Sales,Kolkata,58933,5.9,1
89,EMP0090,Meera Joshi,41,HR,Kolkata,84999,4.5,2
93,EMP0094,Riya Shah,46,Operations,Delhi,37652,2.5,3
96,EMP0097,Kavya Agarwal,42,Marketing,Hyderabad,32256,2.3,1
97,EMP0098,Rohan Agarwal,42,IT,Pune,44986,7.7,4

In [69]:
df1.head()[[True,False,True,True,False]]

,Employee_ID,Name,Age,Department,City,Salary,Experience_Years,Performance_Rating
0,EMP0001,Simran Sharma,34,Sales,Delhi,57013,6.9,4
2,EMP0003,Vikram Bansal,32,Data Science,Jaipur,48178,9.0,4
3,EMP0004,Kavya Gupta,47,IT,Hyderabad,89877,2.6,3

# filter with multiple conditions

Salary > 50000 and the city should be delhi

In [ ]:
df1[(df1['Salary']>50000) & (df1['City']=='Delhi') ]

,Employee_ID,Name,Age,Department,City,Salary,Experience_Years,Performance_Rating
0,EMP0001,Simran Sharma,34,Sales,Delhi,57013,6.9,4
1,EMP0002,Ananya Agarwal,46,Finance,Delhi,98245,7.4,1
13,EMP0014,Sneha Kapoor,28,Data Science,Delhi,73470,13.5,2
37,EMP0038,Meera Reddy,46,Operations,Delhi,81443,3.0,5
67,EMP0068,Kavya Reddy,37,Finance,Delhi,113084,0.8,1
70,EMP0071,Rahul Reddy,41,Finance,Delhi,82795,9.1,4
74,EMP0075,Sneha Patel,22,Sales,Delhi,118307,5.0,5
83,EMP0084,Priya Shah,29,Finance,Delhi,93515,6.3,3
84,EMP0085,Aarav Mehta,42,Marketing,Delhi,83283,10.7,4
91,EMP0092,Riya Reddy,35,HR,Delhi,95639,8.2,4

In [81]:
df1[(df1['Salary']>50000) | (df1['City']=='Delhi')]

,Employee_ID,Name,Age,Department,City,Salary,Experience_Years,Performance_Rating
0,EMP0001,Simran Sharma,34,Sales,Delhi,57013,6.9,4
1,EMP0002,Ananya Agarwal,46,Finance,Delhi,98245,7.4,1
3,EMP0004,Kavya Gupta,47,IT,Hyderabad,89877,2.6,3
4,EMP0005,Isha Patel,35,Operations,Pune,87625,9.2,1
5,EMP0006,Simran Sharma,28,Finance,Pune,69696,8.0,2
...,...,...,...,...,...,...,...,...
93,EMP0094,Riya Shah,46,Operations,Delhi,37652,2.5,3
94,EMP0095,Rahul Chopra,27,Data Science,Bengaluru,91205,4.7,5
95,EMP0096,Vikram Sharma,21,Finance,Kolkata,89516,11.6,1
98,EMP0099,Priya Mehta,31,HR,Jaipur,73111,9.0,3
99,EMP0100,Kavya Sharma,24,Sales,Chandigarh,93694,10.9,4

In [ ]:
df1[~(df1['City']=='Delhi') ]

,Employee_ID,Name,Age,Department,City,Salary,Experience_Years,Performance_Rating
2,EMP0003,Vikram Bansal,32,Data Science,Jaipur,48178,9.0,4
3,EMP0004,Kavya Gupta,47,IT,Hyderabad,89877,2.6,3
4,EMP0005,Isha Patel,35,Operations,Pune,87625,9.2,1
5,EMP0006,Simran Sharma,28,Finance,Pune,69696,8.0,2
6,EMP0007,Sneha Agarwal,38,Sales,Jaipur,91600,1.0,5
...,...,...,...,...,...,...,...,...
95,EMP0096,Vikram Sharma,21,Finance,Kolkata,89516,11.6,1
96,EMP0097,Kavya Agarwal,42,Marketing,Hyderabad,32256,2.3,1
97,EMP0098,Rohan Agarwal,42,IT,Pune,44986,7.7,4
98,EMP0099,Priya Mehta,31,HR,Jaipur,73111,9.0,3
99,EMP0100,Kavya Sharma,24,Sales,Chandigarh,93694,10.9,4

# select multiple values

In [85]:
df1[df1['City'].isin(['Delhi','Jaipur','Pune'])]

,Employee_ID,Name,Age,Department,City,Salary,Experience_Years,Performance_Rating
0,EMP0001,Simran Sharma,34,Sales,Delhi,57013,6.9,4
1,EMP0002,Ananya Agarwal,46,Finance,Delhi,98245,7.4,1
2,EMP0003,Vikram Bansal,32,Data Science,Jaipur,48178,9.0,4
4,EMP0005,Isha Patel,35,Operations,Pune,87625,9.2,1
5,EMP0006,Simran Sharma,28,Finance,Pune,69696,8.0,2
6,EMP0007,Sneha Agarwal,38,Sales,Jaipur,91600,1.0,5
7,EMP0008,Sneha Mishra,37,Finance,Pune,84115,3.6,1
13,EMP0014,Sneha Kapoor,28,Data Science,Delhi,73470,13.5,2
25,EMP0026,Karan Mehta,26,Data Science,Pune,85934,3.1,1
26,EMP0027,Priya Reddy,35,Operations,Jaipur,88670,10.0,5
28,EMP0029,Karan Kapoor,40,Sales,Jaipur,115493,3.0,4
35,EMP0036,Isha Gupta,40,Finance,Pune,52089,4.6,5
37,EMP0038,Meera Reddy,46,Operations,Delhi,81443,3.0,5
39,EMP0040,Vivaan Sharma,39,Marketing,Jaipur,72540,9.0,2
41,EMP0042,Aditi Chopra,32,Data Science,Jaipur,87572,8.7,3
43,EMP0044,Nisha Patel,32,Operations,Jaipur,75003,14.3,5
44,EMP0045,Meera Kapoor,27,Data Science,Jaipur,114037,2.3,2
46,EMP0047,Nisha Sharma,26,Marketing,Pune,36493,8.7,1
50,EMP0051,Aditi Agarwal,49,IT,Jaipur,42359,5.9,1
53,EMP0054,Aarav Agarwal,26,IT,Jaipur,60003,1.5,4
54,EMP0055,Arjun Shah,49,Sales,Pune,67659,5.3,2
55,EMP0056,Nisha Mishra,38,HR,Delhi,39812,6.0,1
58,EMP0059,Karan Singh,49,Finance,Jaipur,110570,8.2,5
59,EMP0060,Kavya Mishra,38,Operations,Delhi,46429,0.1,1
62,EMP0063,Riya Patel,22,IT,Jaipur,105783,6.9,3
67,EMP0068,Kavya Reddy,37,Finance,Delhi,113084,0.8,1
70,EMP0071,Rahul Reddy,41,Finance,Delhi,82795,9.1,4
73,EMP0074,Simran Chopra,48,HR,Jaipur,49562,13.4,3
74,EMP0075,Sneha Patel,22,Sales,Delhi,118307,5.0,5
78,EMP0079,Neha Malhotra,43,HR,Pune,119238,14.3,2
82,EMP0083,Rahul Agarwal,26,Marketing,Jaipur,112820,3.1,3
83,EMP0084,Priya Shah,29,Finance,Delhi,93515,6.3,3
84,EMP0085,Aarav Mehta,42,Marketing,Delhi,83283,10.7,4
85,EMP0086,Rahul Mishra,47,Data Science,Jaipur,86309,14.9,1
91,EMP0092,Riya Reddy,35,HR,Delhi,95639,8.2,4
93,EMP0094,Riya Shah,46,Operations,Delhi,37652,2.5,3
97,EMP0098,Rohan Agarwal,42,IT,Pune,44986,7.7,4
98,EMP0099,Priya Mehta,31,HR,Jaipur,73111,9.0,3

# select within th range

In [ ]:
df1[df1['Age'].between(25,40)]

55

# String

In [91]:
df1[df1['Name'].str.contains('Rahul')]

,Employee_ID,Name,Age,Department,City,Salary,Experience_Years,Performance_Rating
12,EMP0013,Rahul Agarwal,41,Operations,Bengaluru,53080,7.2,3
40,EMP0041,Rahul Verma,40,Operations,Chandigarh,51532,0.5,5
63,EMP0064,Rahul Sharma,33,IT,Kolkata,94071,14.3,3
70,EMP0071,Rahul Reddy,41,Finance,Delhi,82795,9.1,4
71,EMP0072,Rahul Mehta,37,IT,Kolkata,50285,0.6,5
82,EMP0083,Rahul Agarwal,26,Marketing,Jaipur,112820,3.1,3
85,EMP0086,Rahul Mishra,47,Data Science,Jaipur,86309,14.9,1
94,EMP0095,Rahul Chopra,27,Data Science,Bengaluru,91205,4.7,5

# Query operation

In [92]:
df1.query("Age > 40 and Salary > 50000")

,Employee_ID,Name,Age,Department,City,Salary,Experience_Years,Performance_Rating
1,EMP0002,Ananya Agarwal,46,Finance,Delhi,98245,7.4,1
3,EMP0004,Kavya Gupta,47,IT,Hyderabad,89877,2.6,3
8,EMP0009,Pooja Gupta,47,HR,Mumbai,99924,13.9,1
10,EMP0011,Meera Patel,46,Finance,Chandigarh,86784,14.6,4
12,EMP0013,Rahul Agarwal,41,Operations,Bengaluru,53080,7.2,3
21,EMP0022,Aditi Patel,44,Finance,Chandigarh,111148,0.5,2
30,EMP0031,Priya Joshi,43,Marketing,Kolkata,96522,13.6,4
33,EMP0034,Nisha Kapoor,44,HR,Mumbai,108057,12.7,3
37,EMP0038,Meera Reddy,46,Operations,Delhi,81443,3.0,5
42,EMP0043,Vivaan Patel,50,Operations,Kolkata,91709,9.1,4
48,EMP0049,Aditya Mehta,45,Finance,Kolkata,51339,2.5,4
52,EMP0053,Isha Mishra,50,HR,Kolkata,109669,3.7,3
54,EMP0055,Arjun Shah,49,Sales,Pune,67659,5.3,2
56,EMP0057,Aarav Agarwal,47,Sales,Chandigarh,53355,10.9,3
58,EMP0059,Karan Singh,49,Finance,Jaipur,110570,8.2,5
70,EMP0071,Rahul Reddy,41,Finance,Delhi,82795,9.1,4
78,EMP0079,Neha Malhotra,43,HR,Pune,119238,14.3,2
84,EMP0085,Aarav Mehta,42,Marketing,Delhi,83283,10.7,4
85,EMP0086,Rahul Mishra,47,Data Science,Jaipur,86309,14.9,1
86,EMP0087,Meera Patel,49,Operations,Mumbai,79640,8.0,1
87,EMP0088,Aditi Mishra,44,HR,Hyderabad,104801,7.2,1
88,EMP0089,Kavya Verma,45,Sales,Kolkata,58933,5.9,1
89,EMP0090,Meera Joshi,41,HR,Kolkata,84999,4.5,2

# Select specific cell

In [95]:
df2.at['emp9','Department']

'HR'

In [96]:
df2.iat[8,3]

'HR'

# sorting

In [98]:
df1.sort_values('Salary')

,Employee_ID,Name,Age,Department,City,Salary,Experience_Years,Performance_Rating
66,EMP0067,Arjun Gupta,43,HR,Chandigarh,30459,8.6,5
96,EMP0097,Kavya Agarwal,42,Marketing,Hyderabad,32256,2.3,1
57,EMP0058,Sneha Agarwal,36,Operations,Bengaluru,32471,3.1,3
22,EMP0023,Simran Shah,47,IT,Kolkata,33264,12.1,3
75,EMP0076,Aditi Sharma,33,HR,Mumbai,34708,1.9,1
...,...,...,...,...,...,...,...,...
44,EMP0045,Meera Kapoor,27,Data Science,Jaipur,114037,2.3,2
28,EMP0029,Karan Kapoor,40,Sales,Jaipur,115493,3.0,4
74,EMP0075,Sneha Patel,22,Sales,Delhi,118307,5.0,5
78,EMP0079,Neha Malhotra,43,HR,Pune,119238,14.3,2
79,EMP0080,Rohan Mishra,33,Finance,Kolkata,119929,12.4,4

In [99]:
df1.sort_index()

,Employee_ID,Name,Age,Department,City,Salary,Experience_Years,Performance_Rating
0,EMP0001,Simran Sharma,34,Sales,Delhi,57013,6.9,4
1,EMP0002,Ananya Agarwal,46,Finance,Delhi,98245,7.4,1
2,EMP0003,Vikram Bansal,32,Data Science,Jaipur,48178,9.0,4
3,EMP0004,Kavya Gupta,47,IT,Hyderabad,89877,2.6,3
4,EMP0005,Isha Patel,35,Operations,Pune,87625,9.2,1
...,...,...,...,...,...,...,...,...
95,EMP0096,Vikram Sharma,21,Finance,Kolkata,89516,11.6,1
96,EMP0097,Kavya Agarwal,42,Marketing,Hyderabad,32256,2.3,1
97,EMP0098,Rohan Agarwal,42,IT,Pune,44986,7.7,4
98,EMP0099,Priya Mehta,31,HR,Jaipur,73111,9.0,3
99,EMP0100,Kavya Sharma,24,Sales,Chandigarh,93694,10.9,4

# N largest and n smallest recrods

In [100]:
df1.nlargest(5,"Salary")

,Employee_ID,Name,Age,Department,City,Salary,Experience_Years,Performance_Rating
79,EMP0080,Rohan Mishra,33,Finance,Kolkata,119929,12.4,4
78,EMP0079,Neha Malhotra,43,HR,Pune,119238,14.3,2
74,EMP0075,Sneha Patel,22,Sales,Delhi,118307,5.0,5
28,EMP0029,Karan Kapoor,40,Sales,Jaipur,115493,3.0,4
44,EMP0045,Meera Kapoor,27,Data Science,Jaipur,114037,2.3,2

In [102]:
df1.nsmallest(5,'Salary')

,Employee_ID,Name,Age,Department,City,Salary,Experience_Years,Performance_Rating
66,EMP0067,Arjun Gupta,43,HR,Chandigarh,30459,8.6,5
96,EMP0097,Kavya Agarwal,42,Marketing,Hyderabad,32256,2.3,1
57,EMP0058,Sneha Agarwal,36,Operations,Bengaluru,32471,3.1,3
22,EMP0023,Simran Shah,47,IT,Kolkata,33264,12.1,3
75,EMP0076,Aditi Sharma,33,HR,Mumbai,34708,1.9,1

# Select column for sepecific data type

In [103]:
df1.dtypes

Employee_ID               str
Name                      str
Age                     int64
Department                str
City                      str
Salary                  int64
Experience_Years      float64
Performance_Rating      int64
dtype: object

In [104]:
df1.select_dtypes(include='number')

    Age  Salary  Experience_Years  Performance_Rating
0    34   57013               6.9                   4
1    46   98245               7.4                   1
2    32   48178               9.0                   4
3    47   89877               2.6                   3
4    35   87625               9.2                   1
..  ...     ...               ...                 ...
95   21   89516              11.6                   1
96   42   32256               2.3                   1
97   42   44986               7.7                   4
98   31   73111               9.0                   3
99   24   93694              10.9                   4

[100 rows x 4 columns]

In [105]:
df1.select_dtypes(include='str')

   Employee_ID            Name    Department        City
0      EMP0001   Simran Sharma         Sales       Delhi
1      EMP0002  Ananya Agarwal       Finance       Delhi
2      EMP0003   Vikram Bansal  Data Science      Jaipur
3      EMP0004     Kavya Gupta            IT   Hyderabad
4      EMP0005      Isha Patel    Operations        Pune
..         ...             ...           ...         ...
95     EMP0096   Vikram Sharma       Finance     Kolkata
96     EMP0097   Kavya Agarwal     Marketing   Hyderabad
97     EMP0098   Rohan Agarwal            IT        Pune
98     EMP0099     Priya Mehta            HR      Jaipur
99     EMP0100    Kavya Sharma         Sales  Chandigarh

[100 rows x 4 columns]